aneoconsulting/ArmoniK.Core

- Adaptors/MongoDB/src/ObjectStorage.cs
- Adaptors/MongoDB/src/ObjectStorageFactory.cs
- Adaptors/MongoDB/src/ServiceCollectionExt.cs
- Adaptors/MongoDB/tests/InjectionTests.cs
- Adaptors/MongoDB/tests/ObjectStorageTests.cs
- Adaptors/Redis/src/ObjectStorage.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/LoggerExt.cs
- Common/src/Pollster/ComputeRequestQueue.cs
- Common/src/Pollster/DataPrefetcher.cs
- Common/src/Pollster/RequestProcessor.cs
- Common/src/StateMachines/ComputeRequestStateMachine.cs
- Common/src/Storage/IDispatchTable.cs
- Common/src/Storage/IObjectStorage.cs
- Common/src/Storage/ISessionData.cs
- Common/src/Storage/ISessionTable.cs
- Common/src/Storage/LockedWrapperQueueStorage.cs
- Common/src/Storage/QueueMessageHandler.cs
- Common/src/Stream/Worker/TaskHandler.cs
- Common/src/gRPC/Protos/V1/CreateLargeTaskRequest.cs
- Common/src/gRPC/Services/ISubmitter.cs
- Common/src/gRPC/Services/Submitter.cs
- Common/tests/ArmoniK.Core.Common.Tests.csproj
- Common/tests/ObjectStorageTestBase.cs
- Common/tests/Pollster/DataPrefetcherTest.cs
- Common/tests/StateMachines/ComputeRequestStateMachineTest.cs
- Common/tests/Stream/TaskHandlerTest.cs
- Tests/Stream/Client/StreamWrapperTests.cs
- Tests/Stream/Common/WorkerService.cs
- Correct [aneoconsulting/ArmoniK#119](https://github.com/aneoconsulting/ArmoniK/issues/119)
- Add Finite State machine to handle the stream more properly
> Fix null payload + add FSM

- Common/src/LoggerExt.cs
take too much time with reflection to get method name
> Improve LogFunction

- Adaptors/Amqp/src/QueueStorage.cs
- Adaptors/Amqp/src/ServiceCollectionExt.cs
- Adaptors/MongoDB/src/Common/MongoCollectionProvider.cs
- Adaptors/MongoDB/src/LockedQueueStorage.cs
- Adaptors/MongoDB/src/ObjectStorage.cs
- Adaptors/MongoDB/src/ObjectStorageFactory.cs
- Adaptors/MongoDB/src/ResultTable.cs
- Adaptors/MongoDB/src/SessionTable.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Common/src/Injection/ProviderBase.cs
- Common/src/Pollster/RequestProcessor.cs
- Common/src/gRPC/WorkerClientProvider.cs
- Control/Submitter/src/Program.cs
Refactor ProviderBase to make it synchrone.
> Make the ProviderBase synchrone

- Common/tests/Helpers/TestHelperClientStreamWritter.cs
- Common/tests/Pollster/RequestProcessorTests.cs
Complete Reply Streams not tested in #49
> Add more tests for RP

- Tests/HtcMock/Client/src/GridClient.cs
- Tests/HtcMock/Client/src/Options/HtcMock.cs
- Tests/HtcMock/Client/src/Program.cs
- Tests/HtcMock/Server/src/SampleComputerService.cs
It allows to debug the graph of dependencies between tasks without taking too much time
> Add options in Mock to select if we want to take parameters into account

- Adaptors/MongoDB/src/Table/DataModel/ResultDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/SessionDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs
Hashed indices on all ID columns. Sorted indices on all date columns (useful for GUI).
> Add more indices on the database

- Adaptors/Memory/src/ResultTable.cs
- Adaptors/MongoDB/src/ResultTable.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Common/src/Pollster/RequestProcessor.cs
- Common/src/Pollster/TaskHandler.cs
- Common/src/Storage/IResultTable.cs
- Common/src/Storage/ResultStatusCount.cs
- Common/src/Stream/Worker/WorkerStreamWrapper.cs
- Common/src/gRPC/Services/ISubmitter.cs
- Common/src/gRPC/Services/Submitter.cs
- Common/tests/IResultTableTests.cs
- Common/tests/Pollster/RequestProcessorTests.cs
- Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
- Common/tests/Submitter/SubmitterTests.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/278
HandleExceptionAsync is not necessary anymore since the error management is done through a try catch in the ProcessAsync method
> Refactor task error management

- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Storage/ITaskTable.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/288
> add documentation for ITaskTable

- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Common/src/Pollster/TaskHandler.cs
- Common/src/Storage/ITaskTable.cs
- Common/tests/ITaskTableTests.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/290
> Fix dates when task status is updated to Canceled

- Common/src/Pollster/TaskHandler.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/302
> Mark results from cancelled tasks as aborted

- Adaptors/Memory/tests/ArmoniK.Core.Adapters.Memory.Tests.csproj
- Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj
- Adaptors/MongoDB/tests/ArmoniK.Core.Adapters.MongoDB.Tests.csproj
- Adaptors/Redis/src/ArmoniK.Core.Adapters.Redis.csproj
- Adaptors/Redis/tests/ArmoniK.Core.Adapters.Redis.Tests.csproj
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Utils/LoggerInit.cs
- Compute/PollingAgent/src/ArmoniK.Core.Compute.PollingAgent.csproj
- Compute/PollingAgent/src/Program.cs
- Control/Metrics/src/ArmoniK.Core.Control.Metrics.csproj
- Control/Metrics/src/Program.cs
- Control/Submitter/src/ArmoniK.Core.Control.Submitter.csproj
- Control/Submitter/src/Program.cs
- Control/Submitter/tests/ArmoniK.Core.Control.Submitter.Tests.csproj
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
Factorize logger initialization in metrics, pollster and submitter
> Remove some aspnet logs in Information

- Common/src/Pollster/CreateLargeTaskProcessor.cs
- Common/src/Pollster/RequestProcessor.cs
- Common/src/StateMachines/ComputeRequestStateMachine.cs
- Common/src/StateMachines/ProcessReplyCreateLargeTaskStateMachine.cs
- Common/src/StateMachines/ProcessReplyResultStateMachine.cs
- Common/tests/StateMachines/ProcessReplyCreateLargeTaskStateMachineTest.cs
- Tests/HtcMock/Client/src/SessionClient.cs
- Tests/HtcMock/Server/src/SampleComputerService.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/304
> Set task to error when there is an issue during task resubmission

- Documentation/articles/tasks.md
- Documentation/articles/toc.yml
fix https://github.com/aneoconsulting/ArmoniK/issues/36
> Add task doc

- .github/workflows/build.yml
- .github/workflows/build_documentations.yml
- .github/workflows/make-release.yml
- .github/workflows/manual-integration-test.yml
Before merging, we need to change the principal branch and update the settings of the protected branches.
Fix https://github.com/aneoconsulting/ArmoniK/issues/368
> Use main instead of master

- Common/tests/Auth/AuthenticationIntegrationTest.cs
Hotfix PR for failing pipeline
> Ignore failing test in pipeline only

- Adaptors/Amqp/src/Options/Amqp.cs
- Adaptors/Amqp/src/QueueStorage.cs
- Adaptors/Amqp/tests/QueueStorageTests.cs
- Compute/PollingAgent/src/appsettings.json
- Control/Metrics/src/appsettings.json
- Control/Submitter/src/appsettings.json
- docker-compose/docker-compose.yml
May fix https://github.com/aneoconsulting/ArmoniK/issues/382
See the section LinkCredit from https://github.com/Azure/amqpnetlite/blob/master/docs/articles/building_application.md
> LinkCredit parameter to control prefetching

- .editorconfig
- Adaptors/MongoDB/src/ServiceCollectionExt.cs
- Common/src/Auth/Authentication/AuthenticationCache.cs
- Common/src/Auth/Authentication/Authenticator.cs
- Common/tests/Auth/AuthenticationCacheTest.cs
- Common/tests/Auth/AuthenticationIntegrationTest.cs
- Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
- Control/Submitter/src/Program.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/410
> Authentication cache

- Control/Metrics/src/ArmoniKMeter.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/428
> Fix metrics exporter

- .github/workflows/build.yml
- .github/workflows/make-release.yml
- Adaptors/MongoDB/src/PartitionTable.cs
- Adaptors/MongoDB/src/ServiceCollectionExt.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/PipelineIntermediates.cs
- Adaptors/MongoDB/src/Table/DataModel/PartitionDataModelMapping.cs
- Adaptors/MongoDB/tests/PartitionTableTests.cs
- ArmoniK.Core.sln
- Common/src/Exceptions/PartitionNotFoundException.cs
- Common/src/Storage/IPartitionTable.cs
- Common/src/Storage/PartitionData.cs
- Common/src/Storage/PodConfiguration.cs
- Common/tests/PartitionTableTestBase.cs
- Control/PodMetrics/src/ArmoniK.Core.Control.PodMetrics.csproj
- Control/PodMetrics/src/ArmoniK.Core.Control.PodMetrics.csproj.DotSettings
- Control/PodMetrics/src/ArmoniKMeter.cs
- Control/PodMetrics/src/Dockerfile
- Control/PodMetrics/src/Options/MetricsExporter.cs
- Control/PodMetrics/src/Program.cs
- Control/PodMetrics/src/appsettings.json
- Tests/HtcMock/Client/src/GridClient.cs
- Tests/HtcMock/Client/src/Options/HtcMock.cs
- Tests/Stream/Client/CreateSessionTests.cs
- Tests/Stream/Client/StreamWrapperTests.cs
- Tests/Stream/Client/SubmitterExt.cs
- docker-compose/docker-compose.queue-activemqp.yml
- docker-compose/docker-compose.queue-artemis.yml
- docker-compose/docker-compose.queue-rabbitmq.yml
- docker-compose/docker-compose.yml
fix https://github.com/aneoconsulting/ArmoniK/issues/362
> Add partition table and optimal number of pod metrics exporter

- .github/workflows/build.yml
- Adaptors/Amqp/src/PullQueueStorage.cs
- Adaptors/Amqp/src/QueueStorage.cs
- Adaptors/Amqp/tests/QueueStorageTests.cs
- Common/src/Injection/Options/Submitter.cs
- Common/src/Injection/ServiceCollectionExt.cs
- Common/src/gRPC/Services/ISubmitter.cs
- Common/src/gRPC/Services/Submitter.cs
- Common/src/gRPC/Validators/CreateSessionRequestValidator.cs
- Common/tests/CreateSessionRequestValidatorTest.cs
- Common/tests/Helpers/SimpleSubmitter.cs
- Common/tests/Helpers/TestTaskHandlerProvider.cs
- Common/tests/Submitter/SubmitterTests.cs
- Common/tests/TaskOptionsValidatorTest.cs
- Compute/PollingAgent/src/Program.cs
- Control/Metrics/src/Program.cs
- Control/PartitionMetrics/src/Program.cs
- Control/Submitter/src/Program.cs
- docker-compose/docker-compose.override.yml
- docker-compose/docker-compose.yml
fix https://github.com/aneoconsulting/ArmoniK/issues/462
> Support default partition

- Control/PartitionMetrics/src/ArmoniKMeter.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/464
> Fix partition metrics exporter crashing when metrics exporter is unavailable

- Adaptors/Amqp/src/PushQueueStorage.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/463
> Catch timeoutexception when trying to close amqp session

- .editorconfig
- Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
- Common/tests/Helpers/SimpleAmqpClientHelper.cs
- Common/tests/Helpers/TestTaskHandlerProvider.cs
https://github.com/aneoconsulting/ArmoniK/issues/465
> Raise severity of object not disposed

- Adaptors/Amqp/tests/QueueStorageTests.cs
- Adaptors/Memory/src/PushQueueStorage.cs
- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/PartitionTable.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Adaptors/Redis/src/ObjectStorage.cs
- Common/src/Injection/ProviderBase.cs
- Common/src/Storage/IPullQueueStorage.cs
- Common/src/Storage/ISessionTable.cs
- Common/src/Storage/ITaskTable.cs
- Common/tests/Pollster/TaskHandlerTest.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/466
> remove code smells

- Common/src/Pollster/Pollster.cs
- Common/tests/Pollster/PollsterTest.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/480
> Fix task processing endpoint

- Common/src/gRPC/Services/GrpcSubmitterService.cs
- Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/495
> Fix error code sent to grpc clients

- Adaptors/Memory/src/ResultTable.cs
- Adaptors/MongoDB/src/IAsyncCursorExt.cs
- Adaptors/MongoDB/src/IMongoQueryableExt.cs
- Adaptors/MongoDB/src/ObjectStorage.cs
- Adaptors/MongoDB/src/ResultTable.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Storage/IResultTable.cs
- Common/src/gRPC/Services/GrpcResultsService.cs
- Control/Submitter/src/Program.cs
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
fix https://github.com/aneoconsulting/ArmoniK/issues/498
> Add result service

- Control/PartitionMetrics/src/ArmoniKMeter.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/513
> avoid dereferencing null object

- Control/Submitter/src/Dockerfile
- Control/Submitter/src/Program.cs
- docker-compose/docker-compose.yml
- tools/test_healthcheck.sh
https://github.com/aneoconsulting/ArmoniK/issues/593
> Use HTTP1 for health check

- Common/src/Pollster/TaskHandler.cs
- Common/tests/Pollster/TaskHandlerTest.cs
There was some missing try catch in TaskHandler class to manage failures at different times of the execution of the task.
fix https://github.com/aneoconsulting/ArmoniK/issues/596
> Better error management in TaskHandler

- Adaptors/MongoDB/src/AuthenticationTable.cs
- Adaptors/MongoDB/src/ServiceCollectionExt.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/PipelineIntermediates.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs
- Common/src/Auth/Authentication/AuthenticationCache.cs
- Common/src/Auth/Authentication/Authenticator.cs
- Common/src/Auth/Authentication/IAuthenticationTable.cs
- Common/src/Auth/Authentication/UserAuthenticationResult.cs
- Common/src/Auth/Authentication/UserIdentity.cs
- Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
- Common/src/Auth/Authorization/Permissions.cs
- Common/src/Auth/Authorization/RequiresPermissionAttribute.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/616
> Added more documentation for auth

- .github/workflows/build.yml
Fix https://github.com/aneoconsulting/ArmoniK/issues/682
> test action to dump compose logs

- .github/workflows/build.yml
- Adaptors/RabbitMQ/src/ConnectionRabbit.cs
- Adaptors/RabbitMQ/src/ServiceCollectionExt.cs
- docker-compose/activemq/activemq.xml
- docker-compose/docker-compose.override-rabbitmq091.yml
- docker-compose/docker-compose.queue-activemqp.yml
- docker-compose/docker-compose.queue-artemis.yml
- docker-compose/docker-compose.queue-rabbitmq.yml
- docker-compose/docker-compose.yml
- Fix https://github.com/aneoconsulting/ArmoniK/issues/684
- Also added a health check to the RabbitMQ  and the ActiveMQ containers to wait until these services are healthy to start the polling agent and the submitter
> Add SSL to RabbitMQ connection

- tools/justfile
This script leverages on the functionalities of just. See the installation instructions in [just](https://github.com/casey/just).
Closes https://github.com/aneoconsulting/ArmoniK/issues/683
> add just script to ease local deployment

- tools/justfile
fix https://github.com/aneoconsulting/ArmoniK/issues/692
> Some fixes to justfile

- Adaptors/MongoDB/src/AuthenticationTable.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/AuthMongoUtils.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/PipelineIntermediates.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs
- Adaptors/MongoDB/tests/AuthenticationTableTest.cs
- Adaptors/MongoDB/tests/BsonSerializerTest.cs
- Common/src/Auth/Authentication/Authenticator.cs
- Common/src/Auth/Authentication/UserIdentity.cs
- Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
- Common/src/Auth/Authorization/GeneralService.cs
- Common/src/Auth/Authorization/Permissions/Permission.cs
- Common/src/Auth/Authorization/Permissions/PermissionScope.cs
- Common/src/Auth/Authorization/Permissions/ServicesPermissions.cs
- Common/src/Auth/Authorization/RequiresPermissionAttribute.cs
- Common/src/gRPC/Services/GrpcResultsService.cs
- Common/src/gRPC/Services/GrpcSessionsService.cs
- Common/src/gRPC/Services/GrpcSubmitterService.cs
- Common/src/gRPC/Services/GrpcTasksService.cs
- Common/tests/Auth/AuthenticationIntegrationTest.cs
- Common/tests/Auth/AuthenticationTableTestBase.cs
- Common/tests/Auth/MockIdentity.cs
- Common/tests/Auth/PermissionTest.cs
- Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
- Common/tests/Helpers/SimpleResultTable.cs
- Common/tests/Helpers/SimpleSessionTable.cs
- Common/tests/Helpers/SimpleTaskTable.cs
- Added authentication support for sessions, tasks and result services used by Gui
- Fixed MongoDB adapter regarding ObjectIds for authentication
- Revamped permissions code to be more generic
> Gui endpoint authentication support

- .dockerignore
- .gitignore
- Adaptors/LocalStorage/src/ArmoniK.Core.Adapters.LocalStorage.csproj
- Adaptors/LocalStorage/src/ArmoniK.Core.Adapters.LocalStorage.csproj.DotSettings
- Adaptors/LocalStorage/src/ObjectStorage.cs
- Adaptors/LocalStorage/src/ObjectStorageFactory.cs
- Adaptors/LocalStorage/src/Options/LocalStorage.cs
- Adaptors/LocalStorage/src/ServiceCollectionExt.cs
- Adaptors/LocalStorage/tests/ArmoniK.Core.Adapters.LocalStorage.Tests.csproj
- Adaptors/LocalStorage/tests/ArmoniK.Core.Adapters.ObjectLocal.Tests.DotSettings
- Adaptors/LocalStorage/tests/ObjectStorageTests.cs
- Adaptors/MongoDB/src/ObjectStorage.cs
- Adaptors/Redis/src/ObjectStorage.cs
- ArmoniK.Core.sln
- Common/src/Injection/ServiceCollectionExt.cs
- Common/tests/ObjectStorageTestBase.cs
- Compute/PollingAgent/src/ArmoniK.Core.Compute.PollingAgent.csproj
- Compute/PollingAgent/src/Dockerfile
- Compute/PollingAgent/src/Program.cs
- Control/Submitter/src/ArmoniK.Core.Control.Submitter.csproj
- Control/Submitter/src/Dockerfile
- Control/Submitter/src/Program.cs
- docker-compose/docker-compose.yml
- tools/justfile
This PR adds a new adapter to store payloads in a local filesystem. This is intended to replace Redis in case of local deployment.
> Local storage for payloads

- .github/workflows/build.yml
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Auth/Authentication/AuthenticationCache.cs
- Common/src/Auth/Authentication/Authenticator.cs
- Common/src/Auth/Authentication/UserIdentity.cs
- Common/src/Auth/Authorization/Permissions/Permission.cs
- Common/src/Auth/Authorization/Permissions/ServicesPermissions.cs
- Common/src/gRPC/Services/GrpcAuthService.cs
- Common/tests/Auth/AuthenticationCacheTest.cs
- Common/tests/Auth/AuthenticationIntegrationTest.cs
- Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
- Control/Submitter/src/Program.cs
- Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
- Added gRPC authentication service
- Endpoint to know your current permissions
- Added tests for this service
- Fixed badly passed along claims store
> Start of the Authentication service 

- .github/workflows/build.yml
- .github/workflows/make-release.yml
Log to docker hub in release pipeline
> Add docker login in release pipeline

- Adaptors/Amqp/src/QueueMessageHandler.cs
- Adaptors/Memory/src/QueueStorage.cs
- Adaptors/RabbitMQ/src/QueueMessageHandler.cs
- Common/src/Pollster/TaskHandler.cs
- Common/src/Storage/IQueueMessageHandler.cs
- Common/tests/Pollster/TaskHandlerTest.cs
- Common/tests/QueueStorageTestsBase.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/743
> Put task in error when worker is unavailable during task execution

- Adaptors/RabbitMQ/src/ConnectionRabbit.cs
Use AsyncLazy as in https://github.com/aneoconsulting/ArmoniK.Core/pull/196 to fix multiple connections in RabbitMQ adapter
Fix https://github.com/aneoconsulting/ArmoniK/issues/754
> Fix multiple connections in RabbitMQ adapter

- .github/workflows/build.yml
Add sleep in health check tests in the pipeline to let the polling agent start properly
fix https://github.com/aneoconsulting/ArmoniK/issues/758
> Add sleep in health check tests to let the polling agent start properly

- terraform/main.tf
- terraform/modules/storage/queue/activemq/inputs.tf
- terraform/modules/storage/queue/activemq/outputs.tf
- terraform/modules/storage/queue/rabbitmq/inputs.tf
- terraform/modules/storage/queue/rabbitmq/main.tf
- terraform/modules/storage/queue/rabbitmq/outputs.tf
- terraform/parameters.tfvars
- terraform/variables.tf
Fix https://github.com/aneoconsulting/ArmoniK/issues/825
> Enable usage of rabbitmq with either protocol 1.0.0 or 0.9.1

- Adaptors/MongoDB/src/PartitionTable.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Injection/ServiceCollectionExt.cs
- Common/src/Storage/IPartitionTable.cs
- Common/src/gRPC/ListPartitionsRequestExt.cs
- Common/src/gRPC/Services/GrpcPartitionsService.cs
- Common/src/gRPC/Validators/ListPartitionsRequestValidator.cs
- Common/tests/ListPartitionsRequestExt/ToPartitionDataFieldTest.cs
- Common/tests/ListPartitionsRequestExt/ToTaskDataFilterTest.cs
- Common/tests/ListPartitionsRequestValidatorTest.cs
- Control/Submitter/src/Program.cs
- Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
Implement new gRPC API to expose a service to interact with partitions.
Needed by the GUI
fix https://github.com/aneoconsulting/ArmoniK/issues/829
> Implement partition service

- Common/src/ArmoniK.Core.Common.csproj
- Common/src/gRPC/ListTasksRequestExt.cs
- Common/tests/ITaskTableTests.cs
- Common/tests/ListTasksRequestExt/ToTaskDataFilterTest.cs
- Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
APIs changed for the GUI, so this PR implements the changes for the task status for ListTaskRequest that became a repeated field.
fix https://github.com/aneoconsulting/ArmoniK/issues/832
> feat(api): Repeated task status for ListTaskRequest

- justfile
Restore some recipes mistakenly removed in the PR https://github.com/aneoconsulting/ArmoniK.Core/pull/216
> restore purged recipes

- justfile
- terraform/locals.tf
- terraform/main.tf
- terraform/modules/storage/queue/artemis/inputs.tf
- terraform/modules/storage/queue/artemis/main.tf
- terraform/modules/storage/queue/artemis/outputs.tf
- terraform/modules/storage/queue/artemis/versions.tf
- terraform/variables.tf
Fix: https://github.com/aneoconsulting/ArmoniK/issues/844
> Support to use artemis as queue storage in terraform deployment

- Common/src/Storage/PartitionData.cs
- Common/src/gRPC/Services/GrpcPartitionsService.cs
- Common/tests/ITaskTableTests.cs
- Common/tests/PartitionTableTestBase.cs
- Control/Submitter/src/Program.cs
- Tests/Bench/Client/src/Program.cs
- terraform/variables.tf
Partitions service was not added to the control plane. This PR adds it properly.
fix https://github.com/aneoconsulting/ArmoniK.Api/issues/117
fix https://github.com/aneoconsulting/ArmoniK.Api/issues/118
fix https://github.com/aneoconsulting/ArmoniK/issues/843
> fix: Properly add partition service in control plane

- .github/workflows/build.yml
- justfile
- terraform/locals.tf
- terraform/main.tf
- terraform/modules/storage/object/minio/inputs.tf
- terraform/modules/storage/object/minio/main.tf
- terraform/modules/storage/object/minio/outputs.tf
- terraform/modules/storage/object/minio/versions.tf
- terraform/variables.tf
fix #840
for now factory is using docker compose but it will be migrated to terraform.
first version of S3 deployment will be only with docker compose
this PR is to adapt terraform scripts to be ready when the  switch will occurs
mofified files will be somewhere here : [sources]\ArmoniK.Core\terraform\*
epic :
> 840_added minio storage deployment + updated factory

- .gitignore
- tools/README.md
- tools/applyformatpatch.sh
This PR adds a script to download and apply format patch from the last workflow run on the current branch.
> feat(tools): script to download and apply format patch from the last workflow run on the current branch

- Common/src/ArmoniK.Core.Common.csproj
- Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
This PR update the ArmoniK.Api packages to their latest version.
> chore: update api to 3.3.0

- terraform/modules/storage/database/mongo/inputs.tf
- terraform/modules/storage/database/mongo/locals.tf
- terraform/modules/storage/database/mongo/main.tf
- terraform/modules/storage/database/mongo/outputs.tf
- terraform/mongodb/mongo-init.js
- terraform/variables.tf
Fix: https://github.com/aneoconsulting/ArmoniK/issues/849
> Mongo Replicas and health check in terraform deployment

- Common/src/gRPC/Services/Agent.cs
- Common/tests/Helpers/TestDatabaseProvider.cs
- Common/tests/Pollster/AgentTest.cs
This PR adds tests for Agent class.
Fix : https://github.com/aneoconsulting/ArmoniK/issues/357
> test: Add tests for Agent class

- Common/src/gRPC/Services/Agent.cs
- Common/tests/Pollster/AgentTest.cs
> test: Add test for getresourcedata in Agent class

- Common/src/gRPC/Services/Agent.cs
This PR removes some non needed nullable suppression in the Agent class.
> refactor: remove unneeded nullable suppression

- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Injection/ServiceCollectionExt.cs
- Common/src/Storage/ITaskTable.cs
- Common/src/gRPC/Services/GrpcApplicationsService.cs
- Common/src/gRPC/Services/GrpcSessionsService.cs
- Common/src/gRPC/Services/GrpcTasksService.cs
- Common/src/gRPC/Validators/ApplicationsCountTasksByStatusRequestValidator.cs
- Common/src/gRPC/Validators/SessionsCountTasksByStatusRequestValidator.cs
- Common/tests/Auth/AuthenticationIntegrationTest.cs
- Common/tests/Helpers/SimpleTaskTable.cs
- Common/tests/ITaskTableTests.cs
- Common/tests/Pollster/TaskHandlerTest.cs
- Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
- Common/tests/Validators/ApplicationsCountTasksByStatusRequestValidatorTest.cs
- Common/tests/Validators/SessionsCountTasksByStatusRequestValidatorTest.cs
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
This PR implements the new APIs introduced in https://github.com/aneoconsulting/ArmoniK.Api/pull/142
> feat(api): Implement count tasks methods from new api version

- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/IMongoQueryableExt.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Storage/ITaskTable.cs
- Common/src/Utils/IQueryableExt.cs
- Common/src/gRPC/ListApplicationsRequestExt.cs
- Common/src/gRPC/Services/GrpcApplicationsService.cs
- Common/src/gRPC/Validators/ListApplicationsRequestValidator.cs
- Common/tests/Auth/AuthenticationIntegrationTest.cs
- Common/tests/Helpers/SimpleTaskTable.cs
- Common/tests/ListApplicationsRequestExt/ToApplicationFieldTest.cs
- Common/tests/ListApplicationsRequestExt/ToApplicationFilterTest.cs
- Common/tests/Pollster/TaskHandlerTest.cs
- Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
- Common/tests/TestBase/TaskTableTestBase.cs
- Common/tests/Validators/ListApplicationsRequestValidatorTest.cs
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
This PR implements multiple sort field when list applications for GUI.
fix: https://github.com/aneoconsulting/ArmoniK/issues/896
> feat: implement multiple sort field when list applications

- justfile
This PR fixes justfile to properly configure ArmoniK logging level in terraform.
> fix: Properly pass logging level configuration to terraform from justfile

- justfile
- terraform/modules/build_image/versions.tf
- terraform/modules/compute_plane/versions.tf
- terraform/modules/monitoring/fluentbit/versions.tf
- terraform/modules/monitoring/metrics/versions.tf
- terraform/modules/monitoring/partition_metrics/versions.tf
- terraform/modules/monitoring/seq/versions.tf
- terraform/modules/monitoring/zipkin/versions.tf
- terraform/modules/storage/database/mongo/versions.tf
- terraform/modules/storage/object/local/versions.tf
- terraform/modules/storage/object/minio/versions.tf
- terraform/modules/storage/object/redis/versions.tf
- terraform/modules/storage/queue/activemq/versions.tf
- terraform/modules/storage/queue/artemis/versions.tf
- terraform/modules/storage/queue/rabbitmq/versions.tf
- terraform/modules/submitter/versions.tf
- terraform/providers.tf
Updates provider version , it contains fixes related to the HealthChecks.
> chore: Update version of docker's terraform provider

- Tests/Bench/Client/src/Options/BenchOptions.cs
- Tests/Bench/Client/src/Program.cs
This PR add the possibility to batch task submission in Bench test. It provides a default value.
> fix: Batch task submission Bench test

- .dockerignore
- .gitignore
This PR ignore more files in .dockerignore and .gitignore.
> chore: Ignore more files for git and docker

- Adaptors/MongoDB/src/ResultTable.cs
Many mongodb queries of ResultTable were filtering on sessionID and name instead on directly id. This made the queries suboptimal as the index that was used was on sessionId, and thus required a full scan of the session.
> perf: queries on ResultTable

- tools/test_healthcheck.sh
Rewrite health check test script to use the tests for health check from the justfile that are also used in the pipeline.
> chore: rewrite health check test script to use the test from the justfile

- Common/src/Pollster/Pollster.cs
Fix: https://github.com/aneoconsulting/ArmoniK/issues/919
> fix: Use parallel init in pollster

- .docs/content/2.dependencies/1.artemis.md
add the protocols supported by Artemis
> docs: add more details about Artemis protocols

- justfile
One target for each : one for Htcmock, one for Stream and one for Bench.
> feat: add targets in the justfile to build Htcmock, Stream and Bench client images

- Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj
- Tests/Bench/Client/src/Options/BenchOptions.cs
- Tests/Bench/Client/src/Program.cs
Improve performances of results retrieving by getting multiple results at the same time.
> perf: Parallel result retrieving in bench test

- terraform/modules/compute_plane/main.tf
- terraform/modules/storage/database/mongo/locals.tf
- terraform/modules/storage/database/mongo/outputs.tf
- terraform/modules/storage/object/local/output.tf
- terraform/modules/storage/queue/artemis/main.tf
Formatting terraform configuration files
> style: rewrite terraform files to a canonical format

- .github/workflows/build.yml
- .github/workflows/code-formatting.yml
- tools/applyformatpatch.sh
- Move formatting test in its workflow file
- Formatting is run on PR
- Check for terraform formatting
> ci: move formatting in its own workflow and add terraform formatting validation

- .docs/package.json
- .docs/pnpm-lock.yaml
- .docs/tokens.config.ts
Update docs theme version adding fluid layout.
> chore(docs): update version of theme

- .docs/content/0.index.md
- .docs/content/2.dependencies/_dir.yml
- .docs/nuxt.config.ts
- Removed the fluid layout from the index page
- Update Cta link from the index page
- Update icon named in the dir file from the dependencies directory
- Update the path to the favicon
> docs: fix many issues

- .docs/package.json
- .docs/pnpm-lock.yaml
> docs: update pnpm version

- Common/src/ArmoniK.Core.Common.csproj
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
> chore: Update Api version

- Adaptors/MongoDB/tests/IndexTest.cs
- Adaptors/MongoDB/tests/InjectionTests.cs
- Adaptors/MongoDB/tests/MongoDatabaseProvider.cs
- Adaptors/MongoDB/tests/SessionProviderTests.cs
- Adaptors/Redis/tests/ObjectStorageTests.cs
- Adaptors/S3/tests/ObjectStorageTests.cs
- Common/tests/Helpers/TestDatabaseProvider.cs
- Common/tests/Helpers/TestPollingAgentProvider.cs
- Common/tests/Helpers/TestPollsterProvider.cs
- Common/tests/Helpers/TestTaskHandlerProvider.cs
- Common/tests/Submitter/SubmitterTests.cs
Remove some warnings cs8620 that came from changes in `IConfigurationBuilder.AddInMemoryCollection`.
> refactor: remove some warnings on nullable

- Compute/PollingAgent/src/Program.cs
- Control/DependencyChecker/src/Program.cs
- Control/Submitter/src/Program.cs
Need to check if zipkin uri is not null whereas we already check it before.
> refactor: Check if zipkin is not null to please compiler

- tools/restart_failed_pipeline_jobs.sh
- tools/update.py
Add scripts for
- update api from command line (python)
- restart failed pipelines jobs (gh cli + bash)
> chore: add some useful scripts

- Common/src/Storage/TaskLifeCycleHelper.cs
Fix: https://github.com/aneoconsulting/ArmoniK/issues/1060
> refactor: replace list containing ready tasks by a dictionary

- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Adaptors/MongoDB/tests/BsonSerializerTest.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Pollster/TaskHandler.cs
- Common/src/Storage/ITaskTable.cs
- Common/src/Storage/ResultLifeCycleHelper.cs
- Common/src/Storage/TaskData.cs
- Common/src/gRPC/Services/Submitter.cs
- Common/tests/Helpers/SimpleTaskTable.cs
- Common/tests/Pollster/TaskHandlerTest.cs
- Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
- Common/tests/Submitter/SubmitterTests.cs
- Common/tests/TestBase/TaskTableTestBase.cs
- Common/tests/TestBase/TaskWatcherTestBase.cs
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
> feat: Add task duration in database

- .github/workflows/build.yml
- .github/workflows/make-release.yml
- Common/src/Utils/LoggerInit.cs
- Common/tests/LoggerExtTest.cs
- Compute/PollingAgent/src/Dockerfile
- Compute/PollingAgent/src/Program.cs
- Control/Metrics/src/Dockerfile
- Control/PartitionMetrics/src/Dockerfile
- Control/Submitter/src/Dockerfile
- Control/Submitter/src/Program.cs
- Tests/Bench/Client/src/Dockerfile
- Tests/Bench/Server/src/Dockerfile
- Tests/HtcMock/Client/src/Dockerfile
- Tests/HtcMock/Server/src/Dockerfile
- Tests/Stream/Server/Dockerfile
- Utils/src/LoggerExt.cs
- justfile
Enrich logs with Core's version.
> refactor: print version of core in logs

- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Storage/SessionData.cs
- Common/src/gRPC/Services/GrpcSessionsService.cs
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
Update API version to 3.9.0-edge.60 with new features
https://github.com/aneoconsulting/ArmoniK.Api/compare/11f4e89...de40d5c
> feat: update Api to 3.9.0-edge.60

- Common/src/gRPC/Services/GrpcResultsService.cs
Implement new get result rpc from results service
> feat: implement new rpc for results service

- Common/src/gRPC/Services/GrpcVersionsService.cs
- Control/Submitter/src/Program.cs
Implement new service coming from new API
> feat: Implement service to list core and api versions

- Common/src/Storage/TaskData.cs
API added more fields in TaskRaw and TaskSummary objects. This PR fills in these new values.
> feat: Fill the added data in TaskRaw and TaskSummary from Api

- Adaptors/MongoDB/src/Table/DataModel/IndexHelper.cs
- Adaptors/MongoDB/src/Table/DataModel/PartitionDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/ResultDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/SessionDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs
- Adaptors/MongoDB/tests/IndexTest.cs
- Common/src/gRPC/Services/GrpcTasksService.cs
Following https://github.com/aneoconsulting/ArmoniK.Core/pull/357, this PR adds the indexes to make sure that the requests have good performances.
> perf: Add indexes for fields that will be used for sorting in API requests

- Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/IndexHelper.cs
- Adaptors/MongoDB/tests/IndexTest.cs
> fix: Fixed indices names and used helper for authentication table

- .github/workflows/build.yml
Dotnet is already installed and this action takes a while to say that dotnet is already there.
> ci: dotnet is already installed on instances

- .github/workflows/build.yml
- .github/workflows/make-release.yml
- justfile
Finally build ARM images with new dockerfiles.
> ci: push base docker image temporarily to build arm images with buildx

- terraform/modules/storage/queue/rabbitmq/main.tf
- terraform/rabbitmq/rabbitmq.conf
See: https://github.com/aneoconsulting/ArmoniK.Core/pull/328
> refactor: modify some configuration parameters for rabbitmq to avoid credit problems

- renovate.json
> chore: split htc.mock in renovate

- renovate.json
You can look this issue to view the result.
> chore: update renovate config to support tests

- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/TaskTable.cs
- Common/src/Storage/ITaskTable.cs
- Common/src/Storage/TaskData.cs
- Common/src/Storage/TaskDataSummary.cs
- Common/src/Storage/TaskDataSummaryExt.cs
- Common/src/gRPC/Services/GrpcTasksService.cs
- Common/src/gRPC/Services/WatchToGrpc.cs
- Common/tests/GrpcTasksServiceTests.cs
- Common/tests/Helpers/SimpleTaskTable.cs
- Common/tests/Helpers/TestDatabaseProvider.cs
- Common/tests/Pollster/TaskHandlerTest.cs
- Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
- Common/tests/TestBase/TaskTableTestBase.cs
fix: https://github.com/aneoconsulting/ArmoniK.Core/issues/438
> fix: cancel tasks from tasks service mongodb request was not valid

- Tests/Bench/Client/src/Program.cs
Use all the ArmoniK.Utils features to parallelize all the parts of the bench client.
> feat: Fully Parallel Bench Client

- Common/src/Pollster/Pollster.cs
- Common/src/Utils/LocalIpFinder.cs
- Common/tests/TestBase/TaskTableTestBase.cs
> fix: Allow other network than Ethernet.

- Common/src/Injection/ServiceCollectionExt.cs
- Common/src/gRPC/Validators/SubmitTaskRequestValidator.cs
- Common/tests/GrpcTasksServiceTests.cs
- Common/tests/Helpers/TestDatabaseProvider.cs
- Common/tests/Validators/SubmitTasksRequestValidatorTest.cs
> fix: Tasks.SubmitTasks empty task creations throws

- Common/src/Pollster/TaskHandler.cs
> fix: complete management of the acquisition of task in processing

- Adaptors/Memory/src/ResultTable.cs
- Adaptors/Memory/src/TaskTable.cs
- Adaptors/MongoDB/src/ResultTable.cs
- Common/src/Storage/IResultTable.cs
- Common/src/Storage/Result.cs
- Common/src/Storage/ResultTableExtensions.cs
- Common/tests/Helpers/SimpleResultTable.cs
Implement `UpdateManyResults` and use it to implement some `ResultTable` methods.
> refactor: UpdateManyResults

- .github/workflows/build.yml
- tools/monitor.sh
Add monitoring while the tests are running to help debugging the pipeline
> ci: Add monitoring of the pipeline

- Common/src/ArmoniK.Core.Common.csproj
- Common/src/gRPC/Convertors/TaskDataHolderExt.cs
- Common/src/gRPC/EnumFieldExt.cs
- Common/src/gRPC/Services/GrpcTasksService.cs
- Common/src/gRPC/Validators/EventSubscriptionRequestValidator.cs
- Common/tests/ListTasksRequestExt/ToTaskDataFieldTest.cs
- Common/tests/ListTasksRequestExt/ToTaskDataFilterTest.cs
- Common/tests/TestBase/TaskTableTestBase.cs
- Common/tests/Validators/EventSubscriptionRequestValidatorTest.cs
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Client.csproj
- Tests/Connectivity/src/ArmoniK.Core.Tests.Connectivity.csproj
- Tests/CrashingWorker/Client/src/ArmoniK.Samples.CrashingWorker.Client.csproj
- Tests/CrashingWorker/Server/src/ArmoniK.Samples.CrashingWorker.Server.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
https://github.com/aneoconsulting/ArmoniK.Api/releases/tag/3.19.0
> chore: Update API to 3.19.0

- Adaptors/MongoDB/tests/AuthenticationTableTest.cs
- Common/tests/TestBase/AuthenticationTableTestBase.cs
Make sure all tests are properly executed.
Add missing attribute `[Setup]` on the function that setup tests so that the tests are properly initialized and executed. Also fixes tests that were not working after adding the attribute.
Unit tests were executed locally.
Better coverage !
> test: make sure to run MongoDB Auth Table tests

- .github/workflows/scout-cron.yml
Make sure the scout pipeline work properly.
- Chenge the location of the checkout of the repo to access releases
Tests will be performed after because the pipeline need to be on main for testing. Manual trigger will help to test faster.
Notification of security issues.
> ci: move checkout in scout cron job

- Adaptors/Amqp/src/ArmoniK.Core.Adapters.Amqp.csproj
- Adaptors/Amqp/tests/ArmoniK.Core.Adapters.Amqp.Tests.csproj
- Adaptors/LocalStorage/tests/ArmoniK.Core.Adapters.LocalStorage.Tests.csproj
- Adaptors/Memory/tests/ArmoniK.Core.Adapters.Memory.Tests.csproj
- Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj
- Adaptors/MongoDB/tests/ArmoniK.Core.Adapters.MongoDB.Tests.csproj
- Adaptors/PubSub/src/ArmoniK.Core.Adapters.PubSub.csproj
- Adaptors/QueueCommon/src/ArmoniK.Core.Adapters.QueueCommon.csproj
- Adaptors/RabbitMQ/src/ArmoniK.Core.Adapters.RabbitMQ.csproj
- Adaptors/RabbitMQ/tests/ArmoniK.Core.Adapters.RabbitMQ.Tests.csproj
- Adaptors/Redis/src/ArmoniK.Core.Adapters.Redis.csproj
- Adaptors/Redis/tests/ArmoniK.Core.Adapters.Redis.Tests.csproj
- Adaptors/S3/src/ArmoniK.Core.Adapters.S3.csproj
- Adaptors/S3/tests/ArmoniK.Core.Adapters.S3.Tests.csproj
- Adaptors/SQS/src/ArmoniK.Core.Adapters.SQS.csproj
- Base/src/ArmoniK.Core.Base.csproj
- Common/src/ArmoniK.Core.Common.csproj
- Common/tests/ArmoniK.Core.Common.Tests.csproj
- Control/Submitter/tests/ArmoniK.Core.Control.Submitter.Tests.csproj
- Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj
- Tests/Connectivity/src/ArmoniK.Core.Tests.Connectivity.csproj
- Tests/CrashingWorker/Client/src/ArmoniK.Samples.CrashingWorker.Client.csproj
- Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Utils/src/ArmoniK.Core.Utils.csproj
Update dependencies to avoid security issues.
Update all the packages that do not break compilation.
Unit test and integration tests.
Some services may work differently due to dependencies updates.
> chore(deps): update dependencies

- Common/src/Storage/TaskLifeCycleHelper.cs
When a session with more than 400k tasks is resumed, the resume session RPC crashes due to a request too large in the database and fails to change the status of tasks from Paused to Submitted and requeue it.
Batching was introduced to update statuses of the tasks that should be resumed.
Unit tests are passing and large sessions can be resumed.
- The RPC will succeed.
- As batching was introduced, more requests on the database will be performed and the RPC will take more time.
> fix: batch resume session to support resuming session with several 100k tasks

- .github/workflows/build.yml
We observed that Terraform version 1.10.0 was still being installed by the runner for our jobs in our pipelines. With this new update, we now ensure that the latest Terraform version (currently 1.10.1) is installed, as version 1.10.0 presents malfunctions.
- Updated Terraform setup configurations to use the `latest` version in all jobs except for the Docker Windows job.
- For the Docker Windows job, we forced Chocolatey to install Terraform version 1.10.1 instead of 1.10.0, which was problematic.
- Verified that Terraform version 1.10.1 is installed for the Docker Windows job.
- Validated that other jobs use the latest version of Terraform (`latest`).
- Improved stability and reliability of Docker Windows job by using a functioning version of Terraform.
- Ensured that other jobs always …
> fix: ensure latest terraform version installation 

- Utils/src/ServerCertificateValidator.cs
- Simplify the codebase by removing duplicate checks that were already performed earlier in the logic
- Removed two **if** statements checking for null values.
- These conditions were confirmed to be already validated in the execution flow.
- No changes to the functionality.
- Logic wasn't changed in tests in the CI passed.
- No impact on functionality as the redundant checks were unnecessary.
- None
> refactor: remove duplicate null checks

- Adaptors/Redis/src/ObjectBuilder.cs
- Utils/src/ServerCertificateValidator.cs
- terraform/locals.tf
- terraform/main.tf
- terraform/modules/storage/object/embed/output.tf
- terraform/modules/storage/object/local/output.tf
- terraform/modules/storage/object/minio/outputs.tf
- terraform/modules/storage/object/redis/certificates.tf
- terraform/modules/storage/object/redis/inputs.tf
- terraform/modules/storage/object/redis/main.tf
- terraform/modules/storage/object/redis/outputs.tf
- terraform/variables.tf
This PR aims to implement the TLS for Redis and improving the handling of dependencies between the submitter and Redis.
- TLS Implementation:
-  Added support for secure connections to Redis using TLS.
- Configured Redis to use: 
-  a specific configuration indicating the location of certificates
-  certificates for authentication (**ca.pem**, **redis.crt**, **redis.key**). 
- Generic Callback for TLS:
- Used the  generic mechanism of **CertificateValidator** to handle TLS validation.
- Verified container initialization and deployement in local environnement 
- Ran HtcMock tests to ensure proper communication between Redis and the Submitter
- **TLS implemented in ArmoniK Core**
This configuration is similar to the one used by MongoDB
> feat: implem tls for Redis

- Utils/src/ServerCertificateValidator.cs
The log level has been changed to improve visibility during debugging sessions, providing clearer insights into SSL validation issues
Replaced *LogDebug* with *LogWarning* for better error visibility in SSL validation failures.
This change ensures more detailed and relevant information during debugging without altering the core logic.
Logs were tested to confirm appropriate log levels and detailed error messages.
No performance impact; the change only affects log levels for improved debugging.
No change to functionality, just clearer logging for errors.
None
> refactor: change logs type on certificateValidator

- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Injection/ServiceCollectionExt.cs
- Common/src/Pollster/AgentHandler.cs
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Client.csproj
- Tests/Connectivity/src/ArmoniK.Core.Tests.Connectivity.csproj
- Tests/CrashingWorker/Client/src/ArmoniK.Samples.CrashingWorker.Client.csproj
- Tests/CrashingWorker/Server/src/ArmoniK.Samples.CrashingWorker.Server.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
Allow same parametrization as https://github.com/aneoconsulting/ArmoniK.Api/pull/590 but on core side.
- Update API version
- Modify agent code to reflect what was done in https://github.com/aneoconsulting/ArmoniK.Api/pull/590.
- Pipeline tests were used to validate everything is still working fine.
Stabler run with java worker.
> chore: parametrize keepalive options for tcp socket  

- .docs/conf.py
The purpose of this change is to enable search functionality in the HTML output of the Sphinx documentation. By adding `html_search = True` to `conf.py`, we are providing an integrated search feature for easier navigation of the documentation.
This modification simply enables the built-in search functionality in Sphinx by setting `html_search = True` in the `conf.py` configuration file. This allows the generated HTML documentation to include a search box that can be used to quickly find specific content within the docs.
Related Issue: N/A
The change enables an additional feature in the documentation (search functionality). The impact is minimal in terms of performance but improves the user experience by making it easier to find specific sections in the documentation. No new dependencies …
> docs: add search in docs

- .docs/content/1.concepts/8.tls_implem.md
This pull request aims to enhance ArmoniK Core's documentation by providing clear and concise information on the custom TLS implementation.
The documentation covers:
- An overview of TLS and its importance.
-  The process of generating and managing TLS certificates using Terraform.
-  The custom TLS validation mechanism using the CertificateValidator class.
-  Integration of TLS with services like RabbitMQ, MongoDB, Redis, and AMQP.
-  Common TLS errors and their resolutions.
None
Enhances project documentation with detailed TLS information.
None
> docs: add documentation for TLS implementation in ArmoniK Core

- Common/tests/Pollster/PollsterTest.cs
Avoid potential crash during the **Common Tests**.
Implement a retry attribute so that it can retry 3 times in case of a crash.
None
Avoid unexpected crash when pushing a commit on Core.
None
> test: add retry attribute to CancelLongTaskShouldSucceed test

- Common/src/Pollster/TaskHandler.cs
refactor: Add logs in tasks handlers
- Addition of logs to follow the MessageQueueStatus according to the TaskStatus.
Checking the status of MessageHandler
> refactor: Add logs in Tasks Handlers

- Adaptors/Amqp/src/ConnectionAmqp.cs
- Adaptors/RabbitMQ/src/ConnectionRabbit.cs
Change the log level on logs to inform us whether:
- TLS was used or not.
- a certificate was provided or not 
Change the log level from Error to Debug or Warning, 
None
Less error logs on Seq in case we deploy on AWS/GCP
[Any additional information that reviewers should be aware of.]
> refactor: change log level on tls use

- Base/src/Exceptions/ObjectDataNotFoundException.cs
- Common/src/Exceptions/InvalidSessionTransitionException.cs
- Common/src/Exceptions/PartitionNotFoundException.cs
- Common/src/Exceptions/ResultNotFoundException.cs
- Common/src/Exceptions/SessionNotFoundException.cs
- Common/src/Exceptions/SubmissionClosedException.cs
- Common/src/Exceptions/TaskAlreadyExistsException.cs
- Common/src/Exceptions/TaskAlreadyInFinalStateException.cs
- Common/src/Exceptions/TaskCanceledException.cs
- Common/src/Exceptions/TaskNotFoundException.cs
- Common/src/Exceptions/TaskPausedException.cs
- Common/src/Exceptions/TimeoutException.cs
Complete code documentation.
This pull request includes documentation improvements for several exception classes in the `ArmoniK.Core` namespace. The changes add XML documentation comments to provide better descriptions and explanations for each exception class and their constructors.
> docs: add xml-doc for exceptions

- Common/src/Storage/QueueMessageHandlerExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Storage/QueueMessageHandlerExt.cs.
> docs: add xml-doc for Common/src/Storage/QueueMessageHandlerExt.cs

- Common/src/Pollster/Pollster.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/Pollster.cs.
This pull request includes documentation improvements for several exception classes in the  namespace. The changes add XML documentation comments to provide better descriptions and explanations.
> docs: add xml-doc for Common/src/Pollster/Pollster.cs

- Common/src/gRPC/Services/GrpcHealthChecksService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcHealthChecksService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcHealthChecksService.cs

- Common/src/Pollster/AgentIdentifier.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/AgentIdentifier.cs.
This pull request includes documentation improvements for several exception classes in the  namespace. The changes add XML documentation comments to provide better descriptions and explanations.
> docs: add xml-doc for Common/src/Pollster/AgentIdentifier.cs

- Common/src/gRPC/Convertors/OutputExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/OutputExt.cs.
> docs: add xml-doc for Common/src/gRPC/Convertors/OutputExt.cs

- Common/src/Injection/ServiceCollectionExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Injection/ServiceCollectionExt.cs.
> docs: add xml-doc for Common/src/Injection/ServiceCollectionExt.cs

- Common/src/Stream/Worker/WorkerStreamHandler.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Stream/Worker/WorkerStreamHandler.cs.
> docs: add xml-doc for Common/src/Stream/Worker/WorkerStreamHandler.cs

- Common/src/Pollster/RunningTaskProcessor.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/RunningTaskProcessor.cs.
> docs: add xml-doc for Common/src/Pollster/RunningTaskProcessor.cs

- Common/src/Pollster/PostProcessor.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/PostProcessor.cs.
> docs: add xml-doc for Common/src/Pollster/PostProcessor.cs

- Common/src/gRPC/Convertors/HealthStatusExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/HealthStatusExt.cs.
> docs: add xml-doc for Common/src/gRPC/Convertors/HealthStatusExt.cs

- Utils/src/ServerCertificateValidator.cs
With the SSL revamp, only a single CA is allowed in the CA PEM file.
Add support for certificate collection when reading the CA PEM file.
Has been tested with https://github.com/aneoconsulting/ArmoniK.Infra/pull/214
This is retro-compatible and would also be compatible with certificates pre revamp.
> fix: Enable multiple CAs in CA PEM file

- Compute/PollingAgent/src/Program.cs
During agent crash, it can lose connection to the queue and the message representing task in processing will be requeued. In this case, another agent will try to acquire the associated task after receiving the message. The task will be in the Processing status (or a later status in the task lifecycle). The second agent will try to reach the agent that should be treating the task, the first agent. If the first agent is still processing the task, the second agent will consider the message as duplicated and remove it from the queue. If the first agent crash at this point, the task will not be requeued since not in the queue anymore and the task will be lost.
This PR adds a check to verify the status of the agent before returning which tasks are in processing on it. It will make sure that if …
> fix: taskprocessing endpoint should not return tasks when agent is unhealthy to avoid losing task

- Common/src/gRPC/Services/GrpcTasksService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcTasksService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcTasksService.cs

- Common/src/gRPC/Services/GrpcSubmitterService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcSubmitterService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcSubmitterService.cs

- Common/src/gRPC/Services/GrpcSubmitterExtensions.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcSubmitterExtensions.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcSubmitterExtensions.cs

- Common/src/gRPC/Services/GrpcSessionsService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcSessionsService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcSessionsService.cs

- Common/src/gRPC/Services/GrpcResultsService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcResultsService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcResultsService.cs

- Common/src/gRPC/Services/GrpcPartitionsService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcPartitionsService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcPartitionsService.cs

- Common/src/gRPC/Services/GrpcApplicationsService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcApplicationsService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcApplicationsService.cs

- Common/src/gRPC/Services/GrpcAuthService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcAuthService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcAuthService.cs

- Common/src/gRPC/Services/GrpcAgentService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcAgentService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcAgentService.cs

- Common/src/Utils/LoggerInit.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Utils/LoggerInit.cs.
> docs: add xml-doc for Common/src/Utils/LoggerInit.cs

- Common/src/Storage/TaskCreationRequest.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Storage/TaskCreationRequest.cs.
> docs: add xml-doc for Common/src/Storage/TaskCreationRequest.cs

- Common/src/Storage/SessionData.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Storage/SessionData.cs.
> docs: add xml-doc for Common/src/Storage/SessionData.cs

- Tests/Bench/Client/src/Options/BenchOptions.cs
- Tests/Bench/Client/src/Program.cs
Currently, the only test workload that is able to test priorities is the stream client.
Add priority option to bench client, in order to test priorities with multiple client calls.
[When applicable, detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
Will be used to test #923
> test: Add priority option to bench client

- Common/src/Utils/ExpressionsBuilders.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Utils/ExpressionsBuilders.cs.
> docs: add xml-doc for Common/src/Utils/ExpressionsBuilders.cs

- .docs/content/services/results_service.md
- .docs/content/services/sessions_service.md
- .docs/content/services/tasks_service.md
- .docs/content/services/usage.md
- .docs/index.rst
Document how to use our RPCs services and their simplified interactions with the database, the queue and the object storage.
- Add sequence diagrams to explain interactions between client and control plane.
- Add sequence diagrams to explain interactions between sessions service from the control plane and the database, the queue and the object storage.
- Add sequence diagrams to explain interactions between tasks service from the control plane and the database, the queue and the object storage.
- Add sequence diagrams to explain interactions between results service from the control plane and the database, the queue and the object storage.
[When applicable, detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.] …
> docs: add sequence diagrams giving an overview of how to use ArmoniK RPCs and what they do internally

- .docs/content/0.installation/0.index.md
- .docs/content/0.installation/1.local-deployment.md
- .docs/content/0.installation/2.tests.md
- .docs/content/0.installation/3.execute-tests.md
- .docs/content/0.installation/6.create-windows-vm.md
- .docs/content/1.concepts/1.components.md
- .docs/content/1.concepts/3.authentication.md
- .docs/content/1.concepts/4.adaptors.md
- .docs/content/1.concepts/5.rabbitmq.md
- .docs/content/1.concepts/7.plugins.md
Documentation clean up
- Fix broken links
- Rephrase some text and correct small typos
[Any additional information that reviewers should be aware of.]
> docs: fix broken links and rephrase confusing paragraphs

- Adaptors/Amqp/src/PullQueueStorage.cs
- Adaptors/Amqp/src/QueueMessageHandler.cs
- Adaptors/PubSub/src/PullQueueStorage.cs
- Adaptors/PubSub/src/QueueMessageHandler.cs
- Adaptors/RabbitMQ/src/PullQueueStorage.cs
- Adaptors/RabbitMQ/src/QueueMessageHandler.cs
- Adaptors/SQS/src/PullQueueStorage.cs
- Adaptors/SQS/src/QueueMessageHandler.cs
We suspect that some message handlers are not properly disposed.
Add a finalizer in all the message handlers to detect when such an handler has been finalized without being disposed.
A Bench client has been ran, but no finalizer were called.
> chore: Add error log messageHandler finalizer

- Adaptors/MongoDB/src/Options/MongoDB.cs
- Adaptors/MongoDB/src/Options/TableStorage.cs
- Adaptors/QueueCommon/src/Amqp.cs
- Adaptors/Redis/src/Options/Redis.cs
- Common/src/Injection/Options/AdapterSettings.cs
- Common/src/Injection/Options/InitWorker.cs
To have better documentation
Add missing inline documentation
Not applicable
None
None
> docs: add missing inline documentation for adapter options

- Common/tests/Pollster/TaskHandlerTest.cs
Added retries to some tests to improve their reliability and reduce flaky failures.
Implemented retry logic on unstable tests to allow automatic reruns upon failure, increasing the chances of passing without manual intervention.
Verified locally that tests now pass more consistently with retries enabled. No new tests were added.
Improves overall test stability and CI reliability with minimal impact on performance or configuration.
Retries are configured with a conservative limit to avoid masking genuine test issues.
* [] I have commented my code, particularly in hard-to-understand areas.
* [] I have made corresponding changes to the documentation.
* [] I have assessed the performance impact of my modifications.
> test: Add retries on LoopCheckOtherAgent TaskHandler test

- Common/src/gRPC/Services/ISubmitter.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/ISubmitter.cs.
> docs: add xml-doc for Common/src/gRPC/Services/ISubmitter.cs

- Common/src/gRPC/Services/GrpcHealthCheckService.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/GrpcHealthCheckService.cs.
> docs: add xml-doc for Common/src/gRPC/Services/GrpcHealthCheckService.cs

- Common/src/gRPC/Convertors/TaskTableExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/TaskTableExt.cs.
> docs: add xml-doc for Common/src/gRPC/Convertors/TaskTableExt.cs

- Common/src/gRPC/Convertors/SessionDataExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/SessionDataExt.cs.
> docs: add xml-doc for Common/src/gRPC/Convertors/SessionDataExt.cs

- Common/src/gRPC/Convertors/ResultExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/ResultExt.cs.
> docs: add xml-doc for Common/src/gRPC/Convertors/ResultExt.cs

- Common/src/Utils/ActivitySourceExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Utils/ActivitySourceExt.cs.
> docs: add xml-doc for Common/src/Utils/ActivitySourceExt.cs

- Common/src/Utils/ActivityExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Utils/ActivityExt.cs.
> docs: add xml-doc for Common/src/Utils/ActivityExt.cs

- Common/src/Storage/TaskLifeCycleHelper.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Storage/TaskLifeCycleHelper.cs.
> docs: add xml-doc for Common/src/Storage/TaskLifeCycleHelper.cs

- Common/src/Pollster/TaskProcessingChecker/TaskProcessingCheckerClient.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/TaskProcessingChecker/TaskProcessingCheckerClient.cs.
> docs: add xml-doc for Common/src/Pollster/TaskProcessingChecker/TaskProcessingCheckerClient.cs

- Common/src/Pollster/AcquisitionStatus.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/AcquisitionStatus.cs.
> docs: add xml-doc for Common/src/Pollster/AcquisitionStatus.cs

- Common/src/Injection/Options/Pollster.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Injection/Options/Pollster.cs.
> docs: add xml-doc for Common/src/Injection/Options/Pollster.cs

- Common/src/HealthCheckRecord.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/HealthCheckRecord.cs.
> docs: add xml-doc for Common/src/HealthCheckRecord.cs

- Common/src/Storage/TaskTableExtensions.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Storage/TaskTableExtensions.cs.
> docs: add xml-doc for Common/src/Storage/TaskTableExtensions.cs

- Common/src/gRPC/ListApplicationsRequestExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/ListApplicationsRequestExt.cs.
> docs: add xml-doc for Common/src/gRPC/ListApplicationsRequestExt.cs

- Common/src/gRPC/ListPartitionsRequestExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/ListPartitionsRequestExt.cs.
> docs: add xml-doc for Common/src/gRPC/ListPartitionsRequestExt.cs

- Common/src/gRPC/Services/Submitter.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Services/Submitter.cs.
> docs: add xml-doc for Common/src/gRPC/Services/Submitter.cs

- Common/src/gRPC/SessionFilterExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/SessionFilterExt.cs.
> docs: add xml-doc for Common/src/gRPC/SessionFilterExt.cs

- Common/src/gRPC/TaskFilterExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/TaskFilterExt.cs.
> docs: add xml-doc for Common/src/gRPC/TaskFilterExt.cs

- Common/src/Pollster/TaskHandler.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/Pollster/TaskHandler.cs.
> docs: add xml-doc for Common/src/Pollster/TaskHandler.cs

- justfile
- terraform/modules/storage/queue/rabbitmq/locals.tf
Test the compatibility with version 4, that have upgrades in performances that we want to use
Change RabbitMQ 4 for windows version from 3.6.12 to 4.1.0
Pipeline
Meilleure version de RabbitMQ
None
> refactor: Implem RabbitMQ 4 for Windows

- Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj
- Adaptors/PubSub/src/ArmoniK.Core.Adapters.PubSub.csproj
- Adaptors/QueueCommon/src/ArmoniK.Core.Adapters.QueueCommon.csproj
- Adaptors/Redis/src/ArmoniK.Core.Adapters.Redis.csproj
- Adaptors/S3/src/ArmoniK.Core.Adapters.S3.csproj
- Adaptors/S3/src/Options/S3.cs
- Adaptors/SQS/src/ArmoniK.Core.Adapters.SQS.csproj
- Adaptors/SQS/src/SQS.cs
- Common/src/ArmoniK.Core.Common.csproj
- Common/src/Injection/Options/AdapterSettings.cs
- Compute/PollingAgent/src/ArmoniK.Core.Compute.PollingAgent.csproj
- Control/Metrics/src/ArmoniK.Core.Control.Metrics.csproj
- Control/Submitter/src/ArmoniK.Core.Control.Submitter.csproj
To complete the documentation
- Enable the build stage to generate the xml documentation on projects still missing i
- Add a few missing inline doc
> docs: Enable xml documentation generation and complete some missing doc

- Adaptors/QueueCommon/src/QueueStorageBase.cs
Complete code documentation. This PR adds missing xml-doc for the file: Adaptors/QueueCommon/src/QueueStorageBase.cs
> docs: complete queue storagebase inline doc

- Adaptors/MongoDB/src/Common/IMongoDataModelMapping.cs
- Adaptors/MongoDB/src/Common/MongoCollectionProvider.cs
- Adaptors/MongoDB/src/Common/SessionProvider.cs
- Adaptors/MongoDB/src/Options/TableStorage.cs
- Adaptors/MongoDB/src/PartitionTable.cs
- Adaptors/MongoDB/src/ResultTable.cs
- Adaptors/MongoDB/src/ServiceCollectionExt.cs
- Adaptors/MongoDB/src/SessionTable.cs
Complete xml documentation for mongo db related classes
> docs: add missing xml doc for mongodb related classes

- Adaptors/MongoDB/src/Common/MongoCollectionProvider.cs
- Adaptors/MongoDB/src/Table/DataModel/IndexHelper.cs
- Adaptors/MongoDB/src/Table/DataModel/PartitionDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/ResultDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/SessionDataModelMapping.cs
- Adaptors/MongoDB/src/Table/DataModel/ShardingExt.cs
- Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs
Complete xml documentation for mongo db related classes.
> docs: Add docs for MongoDB Adapter

- Control/Metrics/src/Options/MetricsExporter.cs
Complete code documentation. This PR adds missing xml-doc for the file: Control/Metrics/src/Options/MetricsExporter.cs
> docs: complete metrics server inline docs

- Adaptors/Redis/src/ArmoniK.Core.Adapters.Redis.csproj
- Adaptors/S3/tests/ArmoniK.Core.Adapters.S3.Tests.csproj
- Base/tests/Queue/Queue.csproj
- Common/src/ArmoniK.Core.Common.csproj
- Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj
- Tests/Common/Client/src/ArmoniK.Core.Common.Client.csproj
- Tests/Connectivity/src/ArmoniK.Core.Tests.Connectivity.csproj
- Tests/CrashingWorker/Client/src/ArmoniK.Samples.CrashingWorker.Client.csproj
- Tests/CrashingWorker/Server/src/ArmoniK.Samples.CrashingWorker.Server.csproj
- Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj
- Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj
- Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
Update transitive dependencies with security concerns.
Update relevant packages especially `Calzolari.Grpc.AspNetCore.Validation` that depends on `System.Text.Json` which has CVEs. As of today, we refer to a version of `System.Text.Json` without CVEs.
- Unit test are passing
- We tested binaries for CVEs
- More secure application
> chore: update dependencies

- Adaptors/SQS/src/QueueMessageHandler.cs
Improve the likelihood to acknowledge or delete messages when there is an issue during the execution of the action. This reduce the probability of a message representing a task in Processing being redistributed.
Add a loop to retry message acknowledgement or deletion.
- Pipelines are passing.
- More extensive testing will be made later on where a few more fixes will be implemented.
- Improve ArmoniK stability during connection issues with SQS. For instance, DNS issues that impede acces to AWS services.
> fix: retry message acknowledgment in SQS adapter

- Adaptors/SQS/src/QueueMessageHandler.cs
Improve logging by tagging more task related logs with the task ID and the message ID.
Add a logger scope with the task ID and the message ID in SQS QueueMessageHandler.
Task ID and the message ID appear properly on logs where previously it didn't.
> fix: add scope in SQS QueueMessageHandler logs

- Common/src/Pollster/Pollster.cs
LogFunction returns an IDisposable that was not disposed in Pollster.
Add using for LogFunction calls in Pollster.
> chore: Dispose log function in Pollster
