aneoconsulting/ArmoniK.Core

Adaptors/MongoDB/src/Table/DataModel/DispatchDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/ResultDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/SessionDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs
As we don't need to select ids on ranges, we can have hashed index that provide a nice boost and will allow more performant sharding in the future.
=> Hashed index

Common/src/Pollster/Pollster.cs
en enlevant le throw, l'erreur est effectivement interceptée et le pollster est capable de prendre une nouvelle tache. Si on laisse ce thow, chaque erreur ici va déclencher une global cancellation et crash le polling agent
=> Reduce errors in polling agent

Adaptors/MongoDB/src/ResultTable.cs, Common/tests/IResultTableTests.cs
The factorization of GetResult and GetResults resulted in a very big slow down of Extension Csharp.
This PR specializes GetResult for MongoDB in order to have a faster DB request.
GetResult 17 times faster
=> Specialize mongo getresult

Common/src/Exceptions/ArmoniKException.cs, Common/src/HealthCheck.cs, Common/src/HealthCheckTag.cs, Common/src/IHealthCheckProvider.cs, Common/src/IInitializable.cs, Common/src/Injection/Options/Components.cs, Common/src/Injection/Options/InitWorker.cs, Common/src/Injection/Options/Pollster.cs, Common/src/Injection/Options/Submitter.cs, Common/src/Injection/ProviderBase.cs, Common/src/Injection/ServiceCollectionExt.cs, Common/src/Pollster/AgentHandler.cs, Common/src/StateMachines/ComputeRequestStateMachine.cs, Common/src/StateMachines/ProcessReplyCreateLargeTaskStateMachine.cs, Common/src/Storage/TaskData.cs, Common/src/Storage/TaskStatusCount.cs, Common/src/Utils/LocalIPv4.cs, Common/src/gRPC/Services/Agent.cs, Common/src/gRPC/Validators/CreateSessionRequestValidator.cs, Common/src/gRPC/Validators/CreateTaskRequestValidator.cs, Common/src/gRPC/Validators/ListSessionsRequestValidator.cs, Common/src/gRPC/Validators/ListTasksRequestValidator.cs, Common/src/gRPC/Validators/SessionFilterValidator.cs, Common/src/gRPC/Validators/TaskFilterValidator.cs, Common/src/gRPC/Validators/TaskOptionsValidator.cs
Improves the documentation of public items. It reduces the number of warnings that comes from the addition of `<GenerateDocumentationFile>true</GenerateDocumentationFile>` in the `.csproj` file of the Common project. One of our goals is to eliminate all the warning due to this option by populating all the missing documentation fields.
fix https://github.com/aneoconsulting/ArmoniK/issues/577
=> Add missing doc

Common/src/Pollster/ComputeRequestQueue.cs, Common/src/Pollster/IAgentHandler.cs, Common/src/StateMachines/UmlMermaidGraphStyle.cs, Common/src/Storage/IPullQueueStorage.cs, Common/src/Storage/IPushQueueStorage.cs, Common/src/Storage/IQueueStorage.cs, Common/src/Storage/Output.cs, Common/src/Storage/PartitionTaskStatusCount.cs
Improves the documentation of public items. It reduces the number of warnings that comes from the addition of `<GenerateDocumentationFile>true</GenerateDocumentationFile>` in the `.csproj` file of the Common project. One of our goals is to eliminate all the warning due to this option by populating all the missing documentation fields.
fix https://github.com/aneoconsulting/ArmoniK/issues/577
=> Add more doc

Common/src/Pollster/Pollster.cs
The Pollster was having a log that is not necessary anymore because there is a log of the same error in the HandleError in the TaskHandler. This PR remove this log.
fix https://github.com/aneoconsulting/ArmoniK/issues/605
=> Remove not helping log

.github/workflows/build.yml, .github/workflows/make-release.yml
At some point the previous way to merge docker images as the same tag with different plateforms (x86, arm) stopped working. Therefore, the ARM variant of the docker images was not available anymore in our regular tags.
This PR fixes this issue.
fix https://github.com/aneoconsulting/ArmoniK/issues/625
=> Modified pipeline to merge arm images

Common/src/Pollster/Pollster.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Helpers/TestUnavailableRpcException.cs, Common/tests/Pollster/PollsterTest.cs, Common/tests/Pollster/TaskHandlerTest.cs
When the worker is down, the polling agent was still trying to send tasks to it. Then the tasks failed and the polling agent was putting them in the error status. It was not detecting that there was an issue with the worker, therefore putting multiple tasks in error whereas they would have been able to succeed.
This PRs marks the polling agent as unhealthy and stop sending tasks to the worker when it detects that the worker is unavailable.
fix https://github.com/aneoconsulting/ArmoniK/issues/636
=> Mark the pollster as failed when worker is unavailable

Common/src/Pollster/Pollster.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Helpers/TestUnavailableRpcException.cs, Common/tests/Pollster/PollsterTest.cs, Common/tests/Pollster/TaskHandlerTest.cs
cherry pick jg/fix636 for 0.6.7 release
=> fix for 636 - Mark the pollster as failed when worker is unavailable

.github/workflows/build.yml
This PR improve the pipeline
fix https://github.com/aneoconsulting/ArmoniK/issues/696
=> Some improvements to the pipeline

.github/workflows/build.yml
Versionnning step is broken due to 2.6.0 version of git-version docker
Revert to 2.5.3
=> Fix versionning in pipeline

Adaptors/Redis/src/ObjectStorage.cs, Common/src/gRPC/Services/Submitter.cs, Common/tests/ObjectStorageTestBase.cs
Redis is a in memory database and it should be use as Cold Db when the data won't be used anymore. For input data we know the input should be removed when the task is properly completed. 
This feature removes the input data when the task was marked as completed in the taskTable
=> Remove input payload after completed task in Redis

Adaptors/MongoDB/tests/IndexTest.cs, Adaptors/MongoDB/tests/MongoDatabaseProvider.cs, Adaptors/MongoDB/tests/SessionProviderTests.cs, Common/tests/ArmoniK.Core.Common.Tests.csproj, Common/tests/Helpers/TestPollingAgentProvider.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Submitter/SubmitterTests.cs
For an unknown reason, all mongodb tests on Linux were failing during mongo2go initialization.
This PR uses EphemeralMongo instead of Mongo2Go for the tests. It solved the issue.
see https://github.com/Mongo2Go/Mongo2Go/issues/141
fix https://github.com/aneoconsulting/ArmoniK/issues/745
=> Fix mongo db tests

Adaptors/Amqp/src/ConnectionAmqp.cs, Common/src/Utils/AsyncLazy.cs
An AMQP QueueStorage is initialized twice, and therefore create two connections to the queue. This fixes it by using an AsyncLazy.
=> Fix multiple connections in AMQP adapter

.github/workflows/build.yml
Fix is no longer needed
This reverts commit ce19b70eb42b11c7a5221ed77f73ffbf89ff5b65.
Should we pick a specific version and stick with it ?
=> Revert "Fix versionning in pipeline"

Common/src/Pollster/Pollster.cs, Common/src/Pollster/TaskHandler.cs, Common/src/Pollster/TaskProcessingChecker/TaskProcessingCheckerClient.cs
This PR improves the acquisition of the task when the message is duplicated which happen a lot with the Artemis message queue.
Several polling agents were able to acquire the same thus leading to lots of issues when 2 tasks are being processed at the same time. Previously the endpoint `/taskprocessing` of the polling agent was returning the task id only after the acquisition of the task. In the time between the reception of the message and the acquisition of the task on the first polling agent, a second one was able to try to acquire the task, receive an empty response from the first polling agent, consider that the other polling agent was not running the task and resubmit the task. Now the endpoint returns the task id in the message from the queue before the acquisition, allowing the …
=> Improve task acquisition when messages are duplicated

.github/workflows/build.yml
This PR adds steps in C# format checking. Those steps generate and upload a git patch when the formatting fails. This will quicken the process of fixing formatting. Now, we can download the patch and apply it instead of running the formatting cleanup locally.
fix https://github.com/aneoconsulting/ArmoniK/issues/831
=> Generate and upload patch when format fails

Common/src/Auth/Authorization/Permissions/ServicesPermissions.cs, Common/tests/Auth/AuthenticationIntegrationTest.cs, Common/tests/Helpers/GrpcSubmitterServiceHelper.cs, Common/tests/Helpers/SimplePartitionTable.cs
This PR adds the missing implementation and tests for authentication for the partition service.
fix https://github.com/aneoconsulting/ArmoniK/issues/848
=> feat(auth): implement auth for Partition service

.github/workflows/build.yml, .github/workflows/make-release.yml
This PR attempts to fix docker image retag during release while trying to use `docker buildx imagetools` to edit manifests.
=> fix: CI multi arch build for docker images and releases

Common/src/gRPC/ListPartitionsRequestExt.cs, Common/tests/ListPartitionsRequestExt/ToTaskDataFilterTest.cs, Common/tests/PartitionTableTestBase.cs
Filter on ParentPartitionId in ListPartionsRequest was not implemented. This PR fixes this issue.
=> fix: add missing filter in ListPartionsRequest

.gitignore
This PR adds some terraform file created during deployment in .gitignore.
=> chore: add terraform output files in .gitignore

Adaptors/S3/src/ObjectStorage.cs
AWS S3 API has a limit of 1000 items to delete in his batch delete mode.
So if we want to delete more than 1000 items we have to chunk by 1000 or less.
=> chunk items to delete by 1000

.dockerignore, ArmoniK.Core.sln, Tests/Bench/Client/src/ArmoniK.Samples.Bench.Client.csproj, Tests/Bench/Client/src/Dockerfile, Tests/Bench/Client/src/Program.cs, Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj, Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj.DotSettings, Tests/Common/Client/src/GrpcChannelExt.cs, Tests/HtcMock/Client/src/ArmoniK.Samples.HtcMock.Client.csproj, Tests/HtcMock/Client/src/Dockerfile, Tests/HtcMock/Client/src/GridClient.cs, Tests/HtcMock/Client/src/SessionClient.cs
This PR adds helpers to compute the throughput of the session and during the session (it counts task from other sessions if any). It also computes ratio between time spent on a task and processing time as well as the time spent between the end of the last dependency and the start of aggregation tasks.
Bench and HtcMock tests use this helper at their end.
=> feat: Add helper for getting stats such as throughput

Tests/Stream/Client/CreateSessionTests.cs, Tests/Stream/Client/StreamWrapperTests.cs
This PR fixes another warning encountered in tests when initializing ConfigurationBuilder with a dictionary. The value can be nullable. This PR adds the missing ?.
This fixes the warning "Argument of type 'Dictionary<string, string>' cannot be used for parameter 'initialData' of type 'IEnumerable<KeyValuePair<string, string?>>' in 'IConfigurationBuilder MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder configurationBuilder, IEnumerable<KeyValuePair<string, string?>>? initialData)' due to differences in the nullability of reference types.".
=> fix: warning when using AddInMemoryCollection with ConfigurationBuilder

Common/tests/Helpers/ForwardingLoggerProvider.cs
This PR fix the missing nullable constraint from ILogger interface for the FowardingLogger class. It removes the warning "Nullability in constraints for type parameter 'TState' of method 'ForwardingLoggerProvider.ForwardingLogger.BeginScope<TState>(TState)' doesn't match the constraints for type parameter 'TState' of interface method 'ILogger.BeginScope<TState>(TState)'. Consider using an explicit interface implementation instead."
=> fix: missing nullability constraint of ILogger implem for tests

.github/workflows/semantic-pull-request.yml
This PR adds GitHub Action workflow to validate PR semantic.
The semantic is based on [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
=> ci: Add semantic pr validation workflow

Adaptors/Amqp/src/ConnectionAmqp.cs, Adaptors/Amqp/src/PullQueueStorage.cs, Adaptors/RabbitMQ/src/ConnectionRabbit.cs, Adaptors/RabbitMQ/src/PullQueueStorage.cs, Common/src/Storage/QueueStorageBase.cs, Common/tests/Helpers/SimpleAmqpClient.cs, Common/tests/Helpers/SimpleRabbitClient.cs, Common/tests/QueueStorageTestsBase.cs, terraform/locals.tf, terraform/modules/compute_plane/locals.tf, terraform/modules/compute_plane/main.tf, terraform/variables.tf
If the connection to queue was lost,  the logs were flooded with the message "Error while pulling the messages from the queue". The reason was that we were not calling the right health check  before executing the pollster's main loop. The aim of this PR is to correct this behavior.
Fix https://github.com/aneoconsulting/ArmoniK/issues/857
=> fix: healthiness prove in queue adaptors

.github/workflows/build.yml
Logs for htc mock are not stored in the right bucket. This PR fixes this issue.
=> fix: store logs in the right bucket

.github/workflows/build.yml
This PR reduces the timeouts for tests (stream, bench and htcmock). Their execution time is significantly lower than the previous timeout. This PR brings the timeouts closer to the execution time to detect failed tests sooner.
=> ci: Reduce timeouts for tests

Common/src/Pollster/Pollster.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Helpers/ExceptionAsyncPipe.cs, Common/tests/Helpers/ExceptionWorkerStreamHandler.cs, Common/tests/Pollster/PollsterTest.cs, Common/tests/Pollster/TaskHandlerTest.cs, Compute/PollingAgent/src/Program.cs
This PR adds an endpoint in the Agent to cancel the current task if the task is in cancelling state. It updates the taskData in the TaskHandler and eventually trigger the cancellation token if the task is in cancelling status.
fix https://github.com/aneoconsulting/ArmoniK/issues/510
=> feat: Add endpoint on Polling Agent to kill the current task if task is in cancelling status

terraform/modules/monitoring/seq/inputs.tf
Use a non privileged port for seq to account for the case when deploying with docker in rootless mode
=> chore: change exposed port for seq

.github/workflows/build.yml, .github/workflows/make-release.yml
This PR updates CI to use `feat:` instead of `feature:` to increase the minor part of the version during the version generation.
=> ci: change codacy to use feat for updating minor version instead of feature

.github/workflows/make-release.yml
Change the release creation process so that we can create tags and release through github. This is a step to uniformize release processes accross our repositories.
The release workflow for new merged code on main would be:
- Create a release from github interface
- Choose the proper next version tag according to the features (feat:) present in the history from the last tag.
- Publish the release
- If the tag is valid, docker images with the new tag are released
- If the tag is __not__ valid, tag is deleted and released is put in draft.
=> ci: Change release process so that we can create tags and release through github

.github/workflows/build.yml
currently partition metrics service is not tested in the pipeline.
The goal of this pr is to test it.
to do this a curl will be used. ex : curl http://localhost:9419/metrics
=> feat: add logs of partion metrics call

Common/src/Utils/ExecutionSingleizer.cs, Common/tests/Utils/ExecutionSingleizerTest.cs, Control/Metrics/src/ArmoniKMeter.cs, Control/PartitionMetrics/src/ArmoniKMeter.cs
previously : metrics exporter was calling about 15 times mongodb by cycle of refresh
now : only one call is performed
=> fix: too many queries on metrics exporter on mongodb

Common/src/ArmoniK.Core.Common.csproj, Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj, Tests/Common/Client/src/ArmoniK.Core.Common.Tests.Client.csproj, Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj, Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj, Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj
This PR updates ArmoniK.Api to its latest stable version : 3.5.2 in preparation for the new release
=> chore: update api to 3.5.2

terraform/modules/monitoring/metrics/outputs.tf
Service `partition_metrics` was using the wrong host name to communicate with the `metrics` server. In a  local deployment the later simply uses `localhost` as host name.
=> fix: correct metrics exporter host name

terraform/modules/compute_plane/locals.tf, terraform/variables.tf
The workerCheckDelay variable was wrongly set in the terraform deployment.
In addition a smaller default time span has been defined to ensure the retries
in the WorkerStreamHandler Init function take place before the pollster main loop
starts/stops.
=> fix: workerCheckDelay in deployment

justfile
Add recepies in `just` script allowing to build each of the containers composing
ArmoniK.Core separately. This should ease local developping-building-testing cycle.
=> chore: separate just recepies to build each component

Tests/Common/Client/src/GrpcChannelExt.cs
This PR extracts more information from the task data retrieved in `LogStatsFromSessionAsync` function.
It adds time spent between:
- Dispatched and Processing
- Creating and Submitted
- Processing and Completed
=> refactor: Show more stats from task data in Bench and HtcMock

.dockerignore
When using the `ncdu -X .dockerignore` command, we can see that the `tools` folder was not properly ignored inducing undesired rebuild for the docker images when modifing files in this folder.
=> fix: properly ignore folders in .dockerignore file

.github/workflows/build.yml, .github/workflows/sonar.yml
As sonar cloud now takes a while to complete, its job has been moved to a different workflow file to allow restarting of the build and test jobs as soon as they terminate instead of waiting for sonar to finish.
=> ci: Migrate sonar cloud analysis to its own workflow

tools/logs2seq.py
The internal documentation of the script was outdated in the sense that it referred to the deprecated authentication  process for aws.
=> chore: update doc of script for sso usage

.docs/content/2.dependencies/1.artemis.md, .docs/content/2.dependencies/_dir.yml, .github/workflows/build.yml, terraform/artemis/broker.xml, terraform/modules/storage/queue/artemis/main.tf
Remove artemis from CI tests. See https://github.com/aneoconsulting/ArmoniK.Core/tree/9f0eb347fc96ea948f665c10c4fbb362c71fd11b/.docs/content/2.dependencies/1.artemis.md for more information.
=> ci: remove artemis from deployed tests

.github/workflows/build.yml, justfile
This PR prepares the way to fully deprecate the docker-compose based deployment. In particular the PR removes all references
to docker-compose actions in the pipeline.
=> chore: Clean up docker-compose usage

.github/workflows/code-formatting.yml
Fix the checkout to the branch in Terraform format check.
=> ci: checkout on the right reference in terraform format checker

.github/workflows/build.yml
Store all the logs of Core pipelines in one folder on AWS S3 under the corresponding bucket
=> refactor: change the emplacement of logs of pipelines on AWS S3 

.github/workflows/code-formatting.yml
Patch output name was not the same in pipeline and tools/applypatch.sh script. This is fixed now.
=> ci: fix csharp patch name in code formatting workflow

Adaptors/S3/src/ArmoniK.Core.Adapters.S3.csproj
Fix issue with missing package when SecurityToken is used on S3
=> fix:  issue with AWSSDK.SecurityToken

.github/workflows/build.yml
Sometimes th deployment of the software just on the runner were failing due to a problem of connection with the website provinding the package. The installation was changed to not used deb package but snap package.
=> ci: change the way to install just to avoid the problem with the previous website

Adaptors/Memory/src/TaskTable.cs, Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj, Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs, Adaptors/MongoDB/src/TaskTable.cs, Adaptors/MongoDB/tests/BsonSerializerTest.cs, Adaptors/MongoDB/tests/MongoDatabaseProvider.cs, Common/src/Storage/ITaskTable.cs, Common/src/Storage/TaskData.cs, Common/src/gRPC/Services/Agent.cs, Common/src/gRPC/Services/Submitter.cs, Common/tests/Helpers/SimpleTaskTable.cs, Common/tests/Pollster/TaskHandlerTest.cs, Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs, Common/tests/TestBase/TaskTableTestBase.cs, ProfilingTools/src/ArmoniK.Core.ProfilingTools.csproj
Previous PR was slowing down dependency resolution in case some tasks had *many* dependencies. This PR solves it by replacing the list of dependencies by an object in MongoDB to avoid linear time to remove elements from the dependencies of a task.
This also solves an increase in memory consumption of the agents.
fix https://github.com/aneoconsulting/ArmoniK/issues/1017
=> perf: Optimized dependency resolution

.github/workflows/build.yml
Increases timeout from 3 to 4 for stream tests because tests are successfull but action still times out. Compilation takes 30s and tests around 2m30s so it is really close.
=> ci: increase timeout for stream tests

Adaptors/MongoDB/src/IMongoQueryableExt.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/SessionTable.cs, Adaptors/MongoDB/src/TaskTable.cs
[retlated CR](https://github.com/aneoconsulting/ArmoniK/issues/1057)
idea here is to use dottrace to check if we can improve mongo db requests
basically we can replace :
```
AsQueryable(sessionHandle).Where(sdm => sdm.SessionId == sessionId)
```
by :
`.Find(session => session.SessionId == sessionId)
`
You can notice 2x to 3x perfs in the mongoDB calls :
we are always performing the same requests with different parameters so :
=> I think further improvements may be to use directly mongo syntax with prebuilt requests
=> seems ugly ok but it could be good to check perf diff with this
=> perf: improve mongodb requests using native mongodb find instead of linq queries

.github/workflows/build.yml
Building ARM images is taking a lot of time during our regular runs so this PR changes when they are built. They will be built on main.
=> ci: build arm images on main

tools/logs2seq.py
Linked to: https://github.com/aneoconsulting/ArmoniK.Core/pull/300
We put logs of core in one folder in S3, we need to change the path in this file to download logs from the right folder.
=> fix: fix path of logs in S3

justfile, terraform/locals.tf, terraform/main.tf, terraform/modules/storage/queue/none/outputs.tf, terraform/variables.tf
Arbitrary configuration can be passed to terraform through the variable `TF_VAR_custom_env_vars`. The queue can also be set up to none meaning that configurations for an external queue can be passed with the `TF_VAR_custom_env_vars` env var.
example:
```bash
TF_VAR_custom_env_vars='{ "MyQueueEndpoint" = "endpoint", "MyQueuePass" = "pass", "MyQueueUser" = "user" }' just queue=none plan
```
=> build: support for external queue

Adaptors/MongoDB/src/TaskTable.cs, Common/src/Storage/TaskTableExtensions.cs
The List Task rpc was giving a bad total number: #428.
Also, canceling a session would put all the task of the session in the cancelling state, without first checking if they were finished.
Both had extra consequences on the task counting in the HTCMock and Bench clients where the throughput was miscalculated.
=> fix: Task List and Cancel

terraform/main.tf, terraform/modules/ingress/certificates.tf
- Use network id instead of network name in terraform to avoid issues with networks with the same name
- Avoid using length() function in terraform as it is only interpreted during `terraform apply`, not in `terraform import`
```bash
docker network create custom_network
terraform -chdir=./terraform import docker_network.armonik $(docker network inspect custom_network | jq -r '.[].Id')
```
=> refactor: Allow terraform import for docker network

.docs/content/1.concepts/3.authentication.md, .docs/content/1.concepts/7.plugins.md, README.md
Some links were no longer valid because of the move done in https://github.com/aneoconsulting/ArmoniK.Core/pull/448 and others because they were updated in ArmoniK repository.
=> docs: fix links

Common/src/ArmoniK.Core.Common.csproj, Common/src/gRPC/ExpressionExt.cs, Common/src/gRPC/ListApplicationsRequestExt.cs, Common/src/gRPC/ListPartitionsRequestExt.cs, Common/src/gRPC/ListResultsRequestExt.cs, Common/src/gRPC/ListSessionsRequestExt.cs, Common/src/gRPC/ListTasksRequestExt.cs, Common/tests/Helpers/SimpleTaskTable.cs
Some functions of LinqKit were used to generate predicate expressions for filters. We don't want to use this package anymore.
=> refactor: remove LinqKit

Adaptors/S3/src/ObjectStorage.cs, Adaptors/S3/src/Options/S3.cs
Add `UseChunkEncoding` and `UseChecksum` options to S3 to make the client compatible with GCS
=> feat: Add options to enable GCS support

Adaptors/Memory/src/TaskTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Exceptions/TaskAlreadyInFinalStateException.cs, Common/src/Injection/Options/Pollster.cs, Common/src/Pollster/Pollster.cs, Common/src/Pollster/PostProcessingTaskQueue.cs, Common/src/Pollster/PostProcessor.cs, Common/src/Pollster/RunningTaskProcessor.cs, Common/src/Pollster/RunningTaskQueue.cs, Common/src/Pollster/TaskHandler.cs, Common/src/Pollster/TaskProcessingChecker/TaskProcessingCheckerClient.cs, Common/src/Pollster/TaskQueueBase.cs, Common/tests/Helpers/SimplePullQueueStorageChannel.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Pollster/PollsterTest.cs, Common/tests/Pollster/TaskHandlerTest.cs, Common/tests/TestBase/TaskTableTestBase.cs, Compute/PollingAgent/src/Program.cs, Tests/Common/Client/src/GrpcChannelExt.cs
Some things I read to get to this point.
- https://learn.microsoft.com/en-us/dotnet/core/extensions/workers?pivots=dotnet-7-0
- https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-7.0&tabs=visual-studio
- https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=net-7.0
- https://learn.microsoft.com/en-us/dotnet/core/extensions/channels
=> feat: Task execution pipelining

Common/src/gRPC/Services/GrpcTasksService.cs, Common/tests/GrpcTasksServiceTests.cs
=> fix: Task Service CancelTasks throws when ownerPodId is null or empty

Common/tests/WatchToGrpcTests.cs
On the WatchGrpc test, the check was the following: check that the exception type is exactly an `OperationCanceledException` instead of checking that the exception is an instance of `OperationCanceledException` (including child classes).
https://docs.nunit.org/articles/nunit/writing-tests/constraints/ThrowsConstraint.html
=> test: watch grpc test

Adaptors/MongoDB/src/Common/MongoCollectionProvider.cs
When there was a mismatch in Index options, MongoDB adaptor would refuse to init, and stop the pod. This behavior is a bit extreme and now, it just logs a warning in case of index mismatch.
The level of some logs has been decreased in order to have a cleaner startup. In case of error, the init exception is now forwarded and will be visible in the Fatal log:
=> fix: More resilient MongoDB init

Adaptors/Memory/src/ResultTable.cs, Adaptors/MongoDB/src/ResultTable.cs, Common/src/Storage/IResultTable.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/tests/Helpers/SimpleResultTable.cs, Common/tests/TestBase/ResultTableTestBase.cs
When creating many tasks, the dependency management is slow because it consists of many requests. This PR batch the requests to make this much faster.
Before this, HTCmock generates 10000 subtasks in one go took 2 minutes, now it takes 7s.
=> feat: Batched dependency management

Adaptors/MongoDB/src/PartitionTable.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/SessionTable.cs, Adaptors/MongoDB/src/Table/DataModel/IndexHelper.cs, Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs, Adaptors/MongoDB/src/TaskTable.cs, Adaptors/MongoDB/tests/IndexTest.cs, Common/src/Storage/IPartitionTable.cs, Common/src/Storage/IResultTable.cs, Common/src/Storage/ISessionTable.cs, Common/src/Storage/ITaskTable.cs, Common/tests/Helpers/SimplePartitionTable.cs, Control/Metrics/src/ArmoniKMeter.cs, Control/Metrics/src/Options/MetricsExporter.cs, Control/Metrics/src/Program.cs, terraform/variables.tf
Revamp how the metrics are computed and exported.
This enables to filter out some metrics that are not useful in order to reduce the load on the database.
It also improves the database query to avoid scanning all documents, only the indexed keys are scanned now.
For a database with 1.5M tasks, here are the performance to count all the tasks:
- Before: 1000ms
- After, without proper index: 2000ms
- After, with proper (combined) index: 450ms
=> fix: reduce metrics exported

Common/src/Storage/TaskData.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/tests/TestBase/TaskTableTestBase.cs
on a un pb quand la tache est crée avec une dépendence qui a été complétée avant la soumission de la tache
cette dépendance n'est pas enlevée des remaining dependencies
du coup, la tache qui vient d'etre crée ne peut pas etre mise dans la queue et traitée par ce que la condition pour le faire, c'est que le champ remaning depedencies soit vide
=> fix: remove all completed dependencies from tasks remaining dependencies during submission

Common/tests/Helpers/ExceptionWorkerStreamHandler.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Pollster/TaskHandlerTest.cs
- refactor: remove redondant test
- refactor: rework timers for ExecuteTaskWithExceptionDuringCancellationShouldSucceed
=> refactor: remove redondant test and rework timers for ExecuteTaskWithExceptionDuringCancellationShouldSucceed

Common/src/Storage/ResultCreationRequest.cs, Common/src/gRPC/Services/Agent.cs, Common/src/gRPC/Services/GrpcAgentService.cs, Common/src/gRPC/Services/IAgent.cs, Common/tests/Helpers/SimpleAgent.cs, Common/tests/Pollster/AgentTest.cs
- refactor: remove gRPC objects from IAgent NotifyResultData
- refactor: remove gRPC objects from IAgent CreateResultsMetaData
- refactor: remove gRPC objects from IAgent CreateResults
=> refactor: remove gRPC objects from IAgent

.docs/content/0.installation/4.perftests-htcmock.md, tools/perftest-htcmock.sh
- test: add script to execute perf tests with HtcMock
- docs: add article on test process with htc mock
=> test: add script and article to explain our basic performance test with HtcMock

Common/src/Injection/Options/Submitter.cs, Common/src/gRPC/Services/Submitter.cs
This flag defaults to false as the natural way to delete data in ArmoniK is to use the Results API that allows to delete data or the session API that allows to purge data for an entire session. These are the recommended and explicit ways to manage data now.
=> feat: add flag to toggle payload deletion after successful task

Adaptors/Memory/src/PushQueueStorage.cs, Adaptors/Memory/src/TaskTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Exceptions/TaskAlreadyExistsException.cs, Common/src/Pollster/AcquisitionStatus.cs, Common/src/Pollster/TaskHandler.cs, Common/src/Storage/TaskData.cs, Common/src/Storage/TaskTableExtensions.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Pollster/TaskHandlerTest.cs, Common/tests/TaskLifeCycleHelperTest.cs, Common/tests/TestBase/TaskTableTestBase.cs
Fix the issue in which retried task appear in Creating and are not processed further, preventing application from running to completion.
To my understanding, during downscaling, preemption or crash and when the worker crashes too, the agent can be abruptly stopped during the submission of the retried task (task creation, task finalization or insertion into the queue). We also observe that the agent tries to acquire the initial task with status Retried instead of the new copy of the task (the new attempt). The retried task is only in the Creating status, showing that the task finalization was not properly done. This means that the initial task' finalization has not completed properly.
To mitigate this issue, we implement a recovery mechanism that, when an agent tries to acquire the initial …
=> fix: resubmit task when agent tries to acquire a task in Retried

Adaptors/MongoDB/src/Common/IMongoDataModelMapping.cs, Adaptors/MongoDB/src/Common/MongoCollectionProvider.cs, Adaptors/MongoDB/src/Object/ObjectDataModelMapping.cs, Adaptors/MongoDB/src/Options/MongoDB.cs, Adaptors/MongoDB/src/ServiceCollectionExt.cs, Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/PartitionDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/ResultDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/SessionDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/ShardingExt.cs, Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs, ProfilingTools/src/OpenTelemetryExporter/OpenTelemetryDataModelMapping.cs
Following https://github.com/aneoconsulting/ArmoniK.Infra/pull/168, this PR aims to enable the deployment of a sharded MongoDB as ArmoniK's database.
A more complete motivation is provided in AEP 004 (https://github.com/aneoconsulting/ArmoniK.Community/pull/48). This PR is meant to treat a previsible bottleneck on ArmoniK's database by enabling a sharded architecture to it.
For now, when a sharded database is specified, the following collections will be sharded : 
- Result
- TaskData
- SessionData
This PR adds : 
- A method `ShardCollectionAsync` to the `IMongoDataModelMapping` interface.
- 2 new `MongoOptions` : a string `AuthSource` and a boolean `Sharding`.
- A new class `ShardingExt` containing an extension method `shardCollection` for the `IClientSessionHandle` interface.
When the …
=> feat: Enable MongoDB collection sharding

Common/src/Pollster/TaskHandler.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Pollster/TaskHandlerTest.cs
During TaskHandler Preprocessing, when an input data is not found, the following error is raised:
```
System.NullReferenceException: agent_ is null.
at ArmoniK.Core.Common.Pollster.TaskHandler.HandleErrorInternalAsync(Exception e, TaskData taskData, Boolean resubmit, Boolean requeueIfUnavailable, CancellationToken cancellationToken) in /src/Common/src/Pollster/TaskHandler.cs:line 923
at ArmoniK.Core.Common.Pollster.TaskHandler.HandleErrorRequeueAsync(Exception e, TaskData taskData, CancellationToken cancellationToken) in /src/Common/src/Pollster/TaskHandler.cs:line 887
at ArmoniK.Core.Common.Pollster.TaskHandler.PreProcessing() in /src/Common/src/Pollster/TaskHandler.cs:line 702
at ArmoniK.Core.Common.Pollster.Pollster.MainLoop(CancellationToken cancellationToken) in …
```
=> fix: agent is null when error occurs in PreProcessing

.github/workflows/scout-cron.yml
Make sure the scout pipiline work properly.
Add the missing GitHub token a environment variable.
Tests will be performed after because the pipeline need to be on main for testing.
Notification of security issues.
=> fix: add missing GH token in scout cron

Common/src/Pollster/Pollster.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Pollster/PollsterTest.cs
Since the refactor to use the exception manager, tasks that were acquired, but not processed because the runningTaskProcessor did not finish executing the current task in the allotted time were not release in the ArmoniK sense.
The message from the queue was put back into the queue, but the task itself remained in the dispatched state (acquired by the current agent).
This had two implications: such a task would need more work to be re-acquired by another pod by using the message duplication algorithm, and the timeout was considered like an actual error of the agent, and would make the agent unhealthy after a few acquire timeouts.
This PR adds a proper catch for the timeout, and release the task in the catch.
A new test has been added to ensure that the pollster does not produce any error …
=> fix: Timeout handling after acquisition

.github/workflows/scout-cron.yml
Make sure the scout pipeline work properly.
- Add the missing checkout of the repo to access releases
- Enable manual trigger of the pipeline
Tests will be performed after because the pipeline need to be on main for testing. Manual trigger will help to test faster.
Notification of security issues.
=> ci: add missing checkout in scout cron job and enable workflow_dispatch

Adaptors/Memory/src/TaskTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Storage/TaskData.cs, Common/tests/TestBase/TaskTableTestBase.cs
Remove code that is not necessary anymore to improve maintainability.
TaskData.EscapeKey was needed to ensure keys provided by users were valid. This is not needed anymore beacause IDs are GUID generated by core. This PR removes this unnecessary step.
Unit tests were used.
Reduced code to maintain.
=> refactor: remove TaskData.EscapeKey

Adaptors/RabbitMQ/src/ConnectionRabbit.cs, Adaptors/RabbitMQ/src/IConnectionRabbit.cs, Adaptors/RabbitMQ/src/PullQueueStorage.cs, Adaptors/RabbitMQ/src/PushQueueStorage.cs, Adaptors/RabbitMQ/src/QueueMessageHandler.cs, Common/tests/Helpers/SimpleRabbitClient.cs
When there is an issue with Rabbit connection and it closes, the agent cannot receive new messages because the connection is not recreated. Agent has to restart for Rabbit Adapter to work again.
As for Amqp, an ExecutionSingleizer was used to create a unique connection. It returns the existing connection when the connection is not closed. When the connection is closed, it creates a new one and returns it.
Unit tests and integration tests were run and no issue appears.
Improves ArmoniK resiliency when RabbitMQ encounters issues.
=> fix: recreate rabbit connection when closed

Common/src/Utils/LoggerInit.cs, Common/src/gRPC/Services/GrpcVersionsService.cs
Improve identification of ArmoniK.Core version from logs.
Version was determined through package version which gives the Major.Minor.Patch version while ignoring prerelease suffixes (-SNAPSHOT*). This PR changes uses Product version instead which contains the full version.
The proper version appears in the logs.
Logs and version API now return the full versions.
=> fix: show exact core version in logs

Adaptors/RabbitMQ/src/ConnectionRabbit.cs
Properly initialize rabbit so that its health check does not return Unhealthy all the time preventing the container from starting when there is a health check set up.
Variable `isInitialized_` was not set to `true`, forcing the health check to be `false`.
This variable was not needed as it is enough to check if the model (represents the underlying connection) is not null. When the model is null, the plugin is not initialized yet. This pr replace the variable by the proper checks on the model.
Health checks added by #785 were used to validate that this development properly initialises the health check.
RabbitMQ plugin initialization now works, allowing the usage of the plugin.
=> fix: properly initialize rabbit health check

Common/src/Storage/ResultTableExtensions.cs, Common/src/gRPC/Services/GrpcSessionsService.cs
Previously, cancelling a session from sessions service was only updating the session status, leaving all its submitted and running tasks in autoscaling count. This PR removes tasks of a cancelled session from the autoscaling count by cancelling of the tasks and results from the session.
When calling the Cancel RPC from the session service, we also change task and results statuses in the cancelled session.
On an ArmoniK instance, this new implementation was used and confirmed to change the statuses.
- It will reduce the computing resources consummed because the submitted tasks from a cancelled session will change status to cancelling and not count for autoscaling.
- If previously cancelling tasks are not removed from the queue during downscaling, when a new session is submitted and …
=> fix: cancelling session from sessions service cancel tasks and abort results from the session

Common/src/Pollster/Agent.cs, Common/src/Pollster/IAgent.cs, Common/src/Pollster/TaskHandler.cs, Common/src/gRPC/Services/Submitter.cs, Common/tests/Helpers/SimpleAgent.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Helpers/WrapperAgentHandler.cs, Common/tests/Pollster/TaskHandlerTest.cs
When tasks postprocessing is not executed, children tasks and results are not aborted. It lets a lot of tasks and results in Creating, adding lot of noise when debugging and misleading remnants of failed tasks as tasks that could potentially complete.
Move children (tasks and results) cancellation from Agent.CancelChild to Submitter.CompleteAsync ensuring that children cancellation is called everytime a task is set to Error or Retry. It uses the new CreatedBy field to find all related tasks and results.
- Unit test were added to make sure children were properly cancelled when tasks return an Error.
- Validated using integration tests: HtcMock is able to produce exception during task execution, generating retries. All children tasks were cancelled.
- Improved debugging
- Clearer end of …
=> fix: ensure task in error or retry children are properly cancelled

Common/src/Storage/TaskLifeCycleHelper.cs
Add debug logs to confirm messages inserted into the queue storage.
Add two logs in TaskLifeCycleHelper:
- messages that are created by a tasks
- messages pushed into the queue
They can be activated by the following env vars:
- `Serilog__MinimumLevel__Override__ArmoniK.Core.Common.Pollster.TaskHandler=Debug`
- `Serilog__MinimumLevel__Override__ArmoniK.Core.Common.gRPC.Services.Submitter=Debug`
Logs appear in Seq while deploying locally.
In Debug mode for the logger, the log volume will increase due to the addititon of new logs.
Submitter will need to be removed in order to refactor logger contexts used in TaskLifeCycleHelper so that logs appear either in their context or within the caller context.
=> refactor: add debug logs around message push into the queue storage

.github/workflows/build.yml
Separate pull and run of windows image to improve workflows success rate.
This PR modifies the CI to pull bench windows image before running them to let more time to download the image than the run of it.
Windows workflow now succeed.
Improve windows workflow success rate.
=> ci: pull windows client image in a separate step

Tests/Bench/Client/src/Program.cs
Sessions should be closed. Add session closure to Bench integration test.
Call session close API at the end of the processing in Bench integration tests.
Check on the GUI that the session is properly closed.
This should provide a clearer monitoring to sessions. A session closed will not process anymore tasks.
=> test: close session at the end of bench test

Common/src/gRPC/Convertors/TaskDataHolderExt.cs
Error message was not available in TaskSummary object when task is in Retried Status  while it is available in TaskDetailed.
Change conversion from TaskDataHolder to gRPC TaskSummary object to fill in the error message when it is available instead of only during errors.
GUI shows the error message when it shows TaskSummary objects
Debugging informations are easier to access in the GUI.
=> fix: properly fill error in gRPC TaskSummary object

Common/src/Pollster/AcquisitionStatus.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Pollster/TaskHandlerTest.cs
Follow up of #762. Pending tasks should also be finalized (and inserted into the queue).
During retry process when a task produces an exception, the retry may fail during insertion into the queue system or setting the task to Submitted. When this happen, the task in retried may stay into the queue and re-acquired. We check if the retried task (the new instance) exists and if it exists whith status Creating or Submitted, we finalize its creation. This PR adds also finalize creation of tasks with status Pending.
Unit tests were added to validate were resubmit properly when the new instance of the task in error is Pending.
Should fix part of the issue where tasks stay in Pending or Submitted whitout being processed.
We need to try other queue systems to see if the same issue occur with them.
=> fix: error recovery after retry fail

Common/src/Storage/SessionTableExtensions.cs, Common/src/gRPC/Services/GrpcSessionsService.cs
Allow a running session to be resumed. It also allows to retry Resume RPC when errors occur. Does not put tasks back in Paused status when an error occur.
- Remove the call to change the task status back to paused when there is an exception.
- Allow session status change to Running when the session is already Running
- Tests were performed with the GUI on the ArmoniK infrastructure. It fixes the issue when the Resume RPC times out. The tasks are not put back in Paused.
- Resume is working more reliably.
=> fix: allow to resume a running session

Common/src/Storage/TaskLifeCycleHelper.cs
Improve the coherence of Running tasks and tasks submitted in the queue after resuming the session.
When resuming session through our dedicated RPC and the interruption of this RPC, we were cancelling the insertion into the queue. Since, we set the status of the tasks to Running then insert the tasks into the queue, we were getting tasks in the status Running but not in the queue due to cancelling. This PR ensures that when we change the status of a chunk of tasks during resume, we try our best to insert them into the queue.
Tests were performed during our benchmark campaign with several millions of tasks. All the tasks that were missing in the queue seems to have been properly inserted.
Improve the quality and reliability of the resume session RPC.
If the control plane is stopped during …
=> fix: Resume session should complete task insertion into the queue

Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj, Adaptors/S3/src/ArmoniK.Core.Adapters.S3.csproj, Adaptors/SQS/src/ArmoniK.Core.Adapters.SQS.csproj, Common/src/Injection/ServiceCollectionExt.cs, Common/tests/AdapterLoading/AdapterLoadingTest.cs
Fix AWS nugets package dynamic loading. 
AWSSDK.Core version in S3 and SQS nugets was conflicting with the one in MongoDB nuget dependencies. This PR uses the same version everywhere, fix the issue.
Unit tests were added to validate the proper dynamic loading of SQS.
It should allow the #782 to work properly.
=> fix: set AWSSDK.Core in MongoDB plugin to fix issue when dynamically loading SQS

.github/workflows/build.yml
Fix unit tests based on EphemeralMongo6.
EphemeralMongo installs a MongoDB version compiled for unbuntu 18 which depends on libssl1.1 that is not installed anymore on ubuntu-latest (24) GitHub runners. This PR installs libssl1.1 for the tests on these runners.
Pipeline now works properly.
We will have to remove this dependency when EphemeralMongo updates.
=> test: install libssl1.1 because MongoDB installed by EphemeralMongoDB depends on it

Adaptors/MongoDB/src/ServiceCollectionExt.cs, Utils/src/ServerCertificateValidator.cs, terraform/main.tf, terraform/modules/compute_plane/inputs.tf, terraform/modules/compute_plane/main.tf, terraform/modules/monitoring/metrics/inputs.tf, terraform/modules/monitoring/metrics/main.tf, terraform/modules/monitoring/partition_metrics/inputs.tf, terraform/modules/monitoring/partition_metrics/main.tf, terraform/modules/storage/database/mongo/certificates.tf, terraform/modules/storage/database/mongo/main.tf, terraform/modules/storage/database/mongo/outputs.tf, terraform/modules/storage/database/mongo/versions.tf, terraform/modules/submitter/inputs.tf, terraform/modules/submitter/main.tf
- Remove the use of the LocalTrustStore to manage CA certificates for TLS in connections to MongoDB.
- Test TLS connection to MongoDB directly from Core.
- Support TLS connection to MongoDB from Windows based compute plane.
- Generate custom certificates and use them to enable TLS for MongDB.
- Rewrite validation callback passed to MongoDB driver to support TLS without using the LocalTrustStore on Linux and Windows.
- CI pipelines of this repository are working properly with the new certificates and validation callback.
- This branch was also tested within the infrastructure with Windows based compute plane instances.
- Enable TLS for our current Windows deployment.
None
=> build: add tls for mongo in deployment

Common/src/Pollster/TaskHandler.cs, Common/src/gRPC/Services/GrpcTasksService.cs
Make task cancellation more robust.
When a task is canceled, the control plane sets the task to cancelling, contacts the agent executing the task to cancel its execution, and then marks the task's results as Aborted. The task will not be retried. Task cancellation is final. The client is then notified that it is no longer necessary to wait for the result in question. The SDK takes over and handles the fact that the result will never be obtained.
During task cancellation, if the control plane is unable to establish a network communication with the agent executing the task, the control plane cannot communicate with the agent and produces an error. Then, the entire second part of the invalid result notification process is not executed.
This PR adds  try catch that ignores errors during …
=> fix: Ignore failure to connect to the agent when cancelling tasks

.docs/content/0.installation/5.version-migration.md
Fix a small typo in the documentation.
Doc was writen before the 0.29.0 release was done so it was not accurate. This PR makes the correction.
=> docs: typo migration to 0.30 not 0.29

.github/workflows/build.yml, Common/src/ArmoniK.Core.Common.csproj, Common/src/Pollster/AgentHandler.cs, Dockerfile, Tests/Bench/Server/src/ArmoniK.Samples.Bench.Server.csproj, Tests/Common/Client/src/ArmoniK.Core.Common.Client.csproj, Tests/Connectivity/src/ArmoniK.Core.Tests.Connectivity.csproj, Tests/CrashingWorker/Client/src/ArmoniK.Samples.CrashingWorker.Client.csproj, Tests/CrashingWorker/Server/src/ArmoniK.Samples.CrashingWorker.Server.csproj, Tests/HtcMock/Server/src/ArmoniK.Samples.HtcMock.Server.csproj, Tests/Stream/Client/ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.csproj, Tests/Stream/Server/ArmoniK.Extensions.Common.StreamWrapper.Tests.Server.csproj, justfile, terraform/main.tf, terraform/modules/compute_plane/inputs.tf, terraform/modules/compute_plane/locals.tf, terraform/modules/compute_plane/main.tf, terraform/variables.tf
Java does not support grpc communication between the worker and the agent over unix sockets, this PR builds on the changes introduced in https://github.com/aneoconsulting/ArmoniK.Api/pull/583 to enable the option to use a tcp socket instead.
Mimic the changes in https://github.com/aneoconsulting/ArmoniK.Api/pull/583 and enlarged the kestrel configuration options in the `AgentHandler` such that it also accepts to listen on a tcp socket. In addition this PR separates the volumes used for shared data and unix socket. Before the PR both of them where mounted on `\cache`,  the updated mount point for shared data is `\comm`.   
Terraform deployment and `just` file have been modified to take into account a new variable `socket_type`,  that can be set to either `unixdomainsocket` or `tcp` so the …
=> feat: allow usage of tcp socket between agent and worker

Adaptors/MongoDB/src/AuthenticationTable.cs, Adaptors/MongoDB/src/Common/MongoCollectionProvider.cs, Adaptors/MongoDB/src/PartitionTable.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/ResultWatcher.cs, Adaptors/MongoDB/src/SessionTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Adaptors/MongoDB/src/TaskWatcher.cs, Common/src/Pollster/Pollster.cs, Common/tests/Pollster/PollsterTest.cs, Utils/src/HealthCheckResultCombiner.cs
Give more meaningful information when healthcheck fails due to issues with checks on the mongodb tables.
- Put a meaningful description in HealthCheckResult.Unhealthy() from the Mongo Adapter
- Reimplement Mongo Adapter Checks to call for the check from their dependencies, thus knowing what went wrong.
- Unit tests and CI tests perform with sucess (locally too).
- Calling HeathChecksService should succeed. The following command can be used.
```bash
docker run --net armonik_network fullstorydev/grpcurl -plaintext armonik.control.submitter:1080 armonik.api.grpc.v1.health_checks.HealthChecksService.
CheckHealth
``` 
Output should look like:
```json
{
"services": [
{
"name": "database",
"healthy": "HEALTH_STATUS_ENUM_HEALTHY"
},
{
"name": "object",
"healthy": "HEALTH_STATUS_ENUM_HEALTHY"
},
{ …
```
=> fix: properly implement IHealthCheckProvider.Check in MongoDB adapter

Common/src/Storage/TaskLifeCycleHelper.cs, Common/tests/TaskLifeCycleHelperTest.cs
Reset task data information whenever a session is resumed and the task will be enqueued. 
This bugs happens whenever a task is not correctly released by a worker and the session is paused before the task is resubmitted. This makes the ownerPodId not to be reseted and the task will never be processed.
An unit test was added.
It solves a bug.
=> fix: reset taskData information when session is resumed and task in resubmitted

tools/logs2seq.py
Script re-inserting logs from the pipeline into seq broke when pipeline was rewritten to support windows. The file extension changed.
Add `.json.gz` extension for input files in `log2seq` script.
```
python tools/logs2seq.py $BUCKET core-pipeline 5008 1 htcmock-sqs-redis-Information-tcp.json.gz
```
now works properly.
- Facilitate investigation when there are issues in the pipeline.
=> fix: add missing extension to re-integrate pipeline logs in seq

Common/src/Pollster/AcquisitionStatus.cs, Common/src/Pollster/TaskHandler.cs
Cover the case where the task had status processing on another pod who crashed, but it was released during acquirement
When a task is acquired it might be a task from a pod that crashed who was in the status processing. During this acquisition it is possible that the task status will change as the pod releases the task. This scenario is not being treated by the actual code.
The test was made on test environment with stress tests (each test with 3 million tasks)
No impact, it only fixes a bug.
=> fix: task had status processing on another pod who crashed, but it was released during acquirement

Adaptors/MongoDB/src/ServiceCollectionExt.cs, Adaptors/Redis/src/ObjectBuilder.cs, Adaptors/Redis/src/Options/Redis.cs, Utils/src/ServerCertificateValidator.cs
We added a check for **RemoteCertificateNameMismatch** to further secure our TLS validation and avoid potential mismatches between the certificate name and the domain in use. We also introduced a boolean **allowHostMismatch** that lets users choose between strict domain name matching or allowing a mismatch between the certificate and the domain.
We updated the SSL validation logic to handle RemoteCertificateNameMismatch conditionally.
- When allowHostMismatch is false, we reject certificates that present a mismatched domain name.
- When allowHostMismatch is true, we tolerate this error and remove it from the list of SSL policy errors.
- Verified that certificates with mismatched names are rejected if allowHostMismatch = false.
- Ensured mismatched certificates are allowed if …
=> fix: add validation for certificate name mismatch in TLS validation

Adaptors/PubSub/src/PubSub.cs, Adaptors/PubSub/src/PullQueueStorage.cs
Pub/Sub has a feature to guarantee that messages are delivered exactly once (no duplication). This feature was enabled by the ArmoniK plugin, but it appears the impact is very high on the throughput of the queue, and is not necessary for the scheduling correctness because ArmoniK is already able to deduplicate messages while acquiring tasks from the queue.
This PR exposes 2 options ExactlyOnceDelivery and MessageOrdering when the plugin creates the subscriptions. Those options are disabled by default.
[When applicable, detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your modifications on ArmoniK. This might include effects on performance, configuration, documentation, new …
=> feat: Options to disable exactlyOnceDelivery

Common/src/gRPC/Validators/ListApplicationsRequestValidator.cs, Common/src/gRPC/Validators/ListPartitionsRequestValidator.cs, Common/src/gRPC/Validators/ListResultsRequestValidator.cs, Common/src/gRPC/Validators/ListSessionsRequestValidator.cs, Common/src/gRPC/Validators/ListTasksRequestValidator.cs, Common/tests/Validators/ListApplicationsRequestValidatorTest.cs, Common/tests/Validators/ListPartitionsRequestValidatorTest.cs, Common/tests/Validators/ListResultsRequestValidatorTest.cs, Common/tests/Validators/ListSessionsRequestValidatorTest.cs, Common/tests/Validators/ListTasksRequestValidatorTest.cs
It can be useful to have the count of tasks or results matching a given filter without getting those tasks or results.
Interface-wise, it make sense to ask a page-size of 0 to get only the the count.
Fix for https://github.com/aneoconsulting/ArmoniK.Api/issues/585
Lift the constraint on page size in the message validation.
There is no impact as the change is entirely retro-compatible. All requests that were valid before are still valid, and requests with a pagesize of zero are now valid.
The actual database implementation already supports a pagesize of 0 internally (ex: https://github.com/aneoconsulting/ArmoniK.Core/blob/main/Adaptors/MongoDB/src/TaskTable.cs#L209).
=> fix: Relaxed constraint on list page size

Common/tests/WatchToGrpcTests.cs
Make unit tests more robust on the pipeline.
Use Nunit `Retry` feature on tests that are not stable enough and where several attempt should be made in the pipieline for them to succeed.
Should solve some of the issues from #544.
- Tests seem more stable on the pipeline
- Less need to retry our pipelines
- We may need to increase the number of retries to be sure it works most of the time.
- https://docs.nunit.org/articles/nunit/writing-tests/attributes/retry.html
=> test: Add Retry option for MultipleWatchShouldSucceed unit test that crashes on pipeline

Common/src/Injection/Options/Submitter.cs, Common/src/gRPC/Services/GrpcResultsService.cs, Common/src/gRPC/Services/GrpcTasksService.cs, Common/tests/GrpcTasksServiceTests.cs
We encounter a lot of MongoWaitQueueFullException when we call this method with many clients and a high degree of parallelism with our Bench integration test.
- Use parallel select to insert data into the object storage instead of doing all the insertions at the same time.
- Batch result completion query in databse instead of executing a query for each result at the same time. It was a call to the result completion here that was raising the MongoWaitQueueFullException.
- Unit tests are passing.
- This implementation was tested with the workload that was producing the issue. The issue did not appear.
- Allow larger scale tests where a large amount of tasks and data are submitted in parallel.
=> fix: limit parallelism in ResultsService.CreateResults

Utils/src/ServerCertificateValidator.cs
SSL validation would generate info and warning logs on every validation even in case of success.
Remove useless log, and make success logs as Debug instead of Information
No functional impact. Success validation are now visible only on Debug log level.
=> fix: Reduce log verbosity in certificate validation

justfile
Image build does not work anymore due to missing informations to create SBOM for windows images.
Deactivate SBOM during docker image building.
Images are built successfully now.
Removing SBOM will make docker scout detect it is missing and will be less acurate.
This PR should be reverted as we use SBOM for vulnerabilities detection.
=> build: toggle off SBOM during image build because windows build fails

.github/workflows/build.yml, Adaptors/MongoDB/tests/IndexTest.cs, Adaptors/MongoDB/tests/MongoDatabaseProvider.cs, Adaptors/MongoDB/tests/SessionProviderTests.cs, Common/tests/Helpers/TestDatabaseProvider.cs, Common/tests/Helpers/TestPollingAgentProvider.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Submitter/SubmitterTests.cs
Remove the dependency to libssl1.1 and factorize some duplicated code.
- Install mongoDB locally and add an environment variable to configure EphemeralMongo to use the locally installed binaries. As those binaries are more recent, they do not need libssl1.1.
- Factorize code by using existing helpers to setup Ephemeral mongo instances
Unit tests pass locally.
- Simplify code
- No more dependency to libssl1.1
=> refactor: add environment variable to select mongo binary and factorize some uses of Ephemeral Mongo

Common/src/Storage/ResultTableExtensions.cs, Common/src/gRPC/Services/GrpcResultsService.cs, Common/src/gRPC/Services/Submitter.cs
When a result is deleted from object storage, its OpaqueID should also be deleted from the database. This is especially useful for plugins that stores the result content inside the OpaqueID, like the embedded plugin.
It has already been done in some places, but there are a few missing places.
Remove the OpaqueID in the MarkAsDeleted method.
No regression
When using the Embedded object storage plugin with large payload, this enable the memory freeing within the database that we expect when we delete a result.
=> fix: Remove OpaqueID upon Result deletion

Adaptors/SQS/src/PullQueueStorage.cs, Adaptors/SQS/src/SQS.cs
Add the attribute waitTimeSeconds to activate the long polling mode instead of short polling one.
Declare waitTimeSeconds as an attribute in the Amazon SQS configuration and add it in the constructor of ReceiveMessage request in order to use long polling mode.
The SQS polling method should be long in the configuration.
SQS polling mode will be long instead of short. 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html#sqs-long-polling 
[Any additional information that reviewers should be aware of.]
=> feat: add waitTimeSeconds as attribute in SQS adapter

Adaptors/Amqp/src/ConnectionAmqp.cs
Reassign the certificate validation callback, in order to not assign a default remoteCertificateValidationCallback to our validation callback.
If only ssl options are true and there is a certificate, then we can assign a new value to our remoteCertificateValidationCallback. Otherwise, its default value isn't changed.
Tested locally
None
None
=> refactor: streamline SSL certificate validation callback assignment

Adaptors/MongoDB/src/Options/MongoDB.cs, Adaptors/MongoDB/src/ServiceCollectionExt.cs, terraform/modules/storage/database/mongo/outputs.tf
MongoDB connection string can be very complex with many options. Currently, not all features are supported, and it seems unreasonable to add ad-hoc options to Core to implement them.
Add a MongoDB__ConnectionString option that is parsed directly by MongoDB library.
If the connection string is used, previous options used for URL building are ignored.
The new MongoDB configuration has been tested in pipeline with both the old options and the new option, and works as expected.
It is entirely retro-compatible as the previous method a connection is used when the connection is empty.
=> chore(config): Support for MongoDB connectionString

Adaptors/Amqp/src/PushQueueStorage.cs
AMQP's JDBC supports $[0,9]$ priority range. In order to allow for more levels of priority, we use multiple queues that we
interpret as priority queues: messages in $\text{queue}_k$ will be dequeued before messages in $\text{queue}_j$ for  $k > j$. Each priority queue has its own internal $[0,9]$ priority range provided by the protocol. Before this PR, the assignment of queue and internal priority for a message whose priority is bigger than 9 was incorrect.  
This PR corrects the arithmetic used to decide to which queue and to which internal priority a message should be enqueued. 
Tested locally that the arithmetic gives the correct distribution. No unit tests added.
Tasks with priorities bigger than 9 should now be correctly enqueued.
None
=> fix: AMQP queue priorities

Adaptors/Amqp/src/ConnectionAmqp.cs, Adaptors/QueueCommon/src/Amqp.cs, Adaptors/RabbitMQ/src/ConnectionRabbit.cs, terraform/modules/storage/queue/rabbitmq/outputs.tf
Simplify TLS configuration by checking a single parameter (the scheme) to indicate whether TLS should be applied.
We now only check whether the scheme is AMQPS or not. Afterwards, we verify if there is a certificate to validate the TLS usage. This change reduces the complexity of TLS configuration by focusing on the scheme and certificate presence.
Tested on the Core deployment and also with the new infrastructure version on localhost and AWS to ensure functionality across different environments.
Simplifies TLS configuration, reducing potential errors and improving code clarity. No significant performance impact.
None
=> refactor: simplify SSL handling in AMQP and RabbitMQ connection classes

Common/src/Storage/ResultLifeCycleHelper.cs, Common/src/Storage/SessionTableExtensions.cs, Common/tests/GrpcResultsServiceTests.cs
Properly delete data from object storage related to a session.
Filter on OpaqueId length did not work properly. This PR introduces filters on Result status, thhus finding the results for which to delete data.
A unit test was added to validate the deletion is done properly.
Avoid filling object storage with data that should be deleted.
=> fix: Session's Purge RPC was not deleting data from object storage properly

.readthedocs.yaml, tools/generate-csharp-doc.sh
Reduce the failure rate of documentation builds.
Install dotnet with apt-get through readthedocs `apt_packages`  instead of using curl to download dotnet installer and execute it to install dotnet.  Curl step was failing a lot.
Documentation is building properly.
Decrease the burden of having a "green" pipeline.
=> ci: use readthedocs apt_packages to install dotnet instead of downloading installer manually

Common/src/gRPC/Services/GrpcAgentService.cs, Common/src/gRPC/Services/GrpcApplicationsService.cs, Common/src/gRPC/Services/GrpcAuthService.cs, Common/src/gRPC/Services/GrpcEventsService.cs, Common/src/gRPC/Services/GrpcHealthChecksService.cs, Common/src/gRPC/Services/GrpcPartitionsService.cs, Common/src/gRPC/Services/GrpcResultsService.cs, Common/src/gRPC/Services/GrpcSessionsService.cs, Common/src/gRPC/Services/GrpcSubmitterService.cs, Common/src/gRPC/Services/GrpcTasksService.cs, Common/src/gRPC/Services/GrpcVersionsService.cs
Link to API documentation for gRPC services class using `inheritdoc` xml tag.
=> docs: use inheritdoc to access API doc in gRPC services

terraform/modules/storage/database/mongo/main.tf
Improve pipeline reliability by tuning MongoDB deployment on Windows thus losing less time rerunning them.
- Increase wait time for MongoDB deployment because there is no health check (mongosh is not available in the Windows container) from 30s to 40s.
- Increase serverSelectionTimeoutMS from the 2s default to 10s. Server selection was not working likely because MongoDB was not deployed. This allows more time to deploy MongoDB on Windows in the pipeline.
- Windows job in the pipeline was re-run around 20 times without issues.
=> ci: increase timeouts for mongo deployment on windows

Adaptors/SQS/src/Heart.cs
Resolve issues where we encounter NullReferenceException when CancellationTokenSource is null during Message Dispose in SQS.
- `stoppedHeartCts_` was set too early to null and was done at the right place later on. We remove the bugged set.
- Pipeline and local tests are working properly.
- Less errors
- May improve SQS performances because some messages were not properly acknowledged
=> fix: stoppedHeartCts_ from SQS should not be set to null here

Common/src/Pollster/Agent.cs, Common/src/Storage/ResultTableExtensions.cs, Common/src/gRPC/Services/GrpcResultsService.cs
If a task ends without completing any result, the task fails within the MongoDB driver.
Add a check to avoid calling MongoDB in case the list is empty.
This enables to have tasks without results, and tasks creating sub-tasks where sub-task inputs are already created outside the current task.
=> fix: Support empty list of completed result within a task

Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/src/Storage/TaskTableExtensions.cs
There is a race condition between the task submission and the result upload, where result completion would enqueue a task only if the task was already in pending state, but in some cases, task submission did not change the state to pending yet.
Adjust the check to include the creating state. Add logs during dependency resolution to help the debugging.
The Extension C# stress test failed without this fix, but is now passing.
=> fix: race condition between submit task and upload result

Compute/PollingAgent/src/Program.cs
The system previously responded with a list of task ids even when a cancellation of the instance was requested after the task had started (i.e., a late CTS cancellation). If the agent is stopping or crashing, the task may be requeued anytime and another agent can take the task. The other agent will see the task being processed in the previous implementation, potentially leading to a task removed from the queue by the second agent while the first agent crashes before properly finalizing the task. This fix reduces the probability of being in such a case.
In `/taskprocessing`, we get the `ExceptionManager` and check whether the late CTS is cancelled. If it is cancelled, we return an empty list.
- Tests are passing locally and in the CI.
We may insert tasks twice in the queue at the same …
=> fix: if late cts cancellation is requested, do not respond that we are processing the task, so that the task is retried

Common/src/Pollster/TaskHandler.cs, Common/tests/Pollster/TaskHandlerTest.cs
When the object storage is not accessible during the pre-processing, the task fails without any retry.
Check the type of exception thrown by the object storage. If it is `ObjectDataNotFoundException`, the task fails without any retry like before, but if the exception is anything other than that, the task is retried.
Unit tests have been adapted to reflect the new semantics.
In case of permanent errors (like object storage misconfiguration), the user will see the error after all the retries have been performed instead of directly at the first execution.
=> fix: Retry task upon pre-processing errors

.github/workflows/build.yml, .github/workflows/make-release.yml, .github/workflows/manual-test.yml
Sometimes, snap takes a very long time to download and install packages, leading to pipeline failures.
Example:
```
Run sudo snap install --edge --classic just
error: cannot perform the following tasks:
- Download snap "snapd" (23771) from channel "stable" (download too slow: 3590.39 bytes/sec)
```
Install `just` from [taiki-e action](https://github.com/taiki-e/install-action) instead of snap. This action should not be sensible to any API rate-limiting of any kind.
This should reduce the failure potential of installing just.
=> ci: Install just from taiki-e action instead of snap

Common/src/Pollster/Agent.cs, Common/tests/Pollster/AgentTest.cs
If the result upload fails (eg: Object Storage is temporarily unavailable), sub-tasks are already submitted and remains in pending state. While it is benign as those tasks are never executed, it adds noise when debugging a faulty session.
Upload the results before creating the tasks in the database. As such, if an exception occurs during result upload, the task submission will be skipped.
Add a unit test to ensure no task is created in case of result upload failure.
This order might be a bit faster as all the payloads will be already completed when tasks are actually created, skipping a good portion of the dependency resolution.
=> refactor: Upload results before submitting sub-tasks

justfile, terraform/modules/storage/queue/rabbitmq/inputs.tf
RabbitMQ tests are unstable using RabbitMQ 3, and RabbitMQ now officially supports AMQP 1.
Use RabbitMQ 4 to limit CI failures due to unstable implementation.
No failure after 20 runs on CI.
RabbitMQ 4 should be more stable because of the official support for AMQP 1.0 (https://www.rabbitmq.com/blog/2024/08/05/native-amqp), and it is reportedly much faster than RabbitMQ 3 (https://www.rabbitmq.com/blog/2024/08/21/amqp-benchmarks).
If the AMQP implementation of RabbitMQ works well, we might deprecate the RabbitMQ Adapter to only have the AMQP adapter.
=> chore(deps): RabbitMQ 4

Adaptors/Redis/src/ObjectStorage.cs
If Redis client fails with a `RedisConnectionException`, the request is not retried by `PerformActionWithRetry`.
Add `RedisConnectionException` to the exceptions that are retried by `PerformActionWithRetry`.
The Redis client would be more resilient to transient network issues.
=> fix: Retry upon RedisConnectionException

Common/src/Exceptions/WorkerDownException.cs, Common/src/Pollster/RunningTaskProcessor.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Helpers/ExceptionWorkerStreamHandler.cs, Common/tests/Pollster/PollsterTest.cs, Common/tests/Pollster/TaskHandlerTest.cs
The existing logic for handling task retries was complex and potentially error-prone, making it difficult to maintain and understand. An error appeared with a new Exception that was not retried when it should be, producing infinite loops where the task was not executed. The task should have been retried and set to error when the retry limit was reached.
This PR refactors the task retry mechanism during Agent cancellation by:​
- Simplifying the control flow to make the logic more straightforward.​
- Clarifying conditions under which tasks should be retried, ensuring consistent behavior.​
- Reducing code complexity to improve maintainability and reduce the likelihood of bugs.​
- Checking the status of the worker during pre-processing to ensure it is available. It simplifies a lot of the …
=> refactor: simplify and clarify logic for retrying tasks during Agent cancellation

Common/src/Injection/Options/Pollster.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Pollster/TaskHandlerTest.cs, Compute/PollingAgent/src/Program.cs
During task acquisition, if the agent detects that the task is processing elsewhere, it acknowledges the message with the reasonning that the other is still healthy and processing it. However, there are cases that we failed to detect where the other responds, but might crash at some point afterwards, leading to message loss.
Instead of acknowledging the message, we postpone it (release to the queue), but with a delay. After the delay, the message is released to the queue and another pod will try to acquire the task, and check again the current pod.
As a consequence, we check the status of the task on the pod at a regular interval until it either completes, or crashes/times out.
This should avoid all message loss related to message duplication, transient queue failure, and the race …
=> refactor: postpone message when task is processing elsewhere

Common/src/Pollster/TaskHandler.cs, Common/tests/Pollster/TaskHandlerTest.cs
If a task is pending and the session is closed, the task is requeued indefinitely because the check of the session status is done after the check of the task status.
Check the session status before checking the task status.
There should be no impact on regular workloads, and avoid infinite loops on buggy workloads.
=> fix: Check session status before checking task status

Adaptors/S3/src/ObjectStorage.cs, Adaptors/S3/src/Options/S3.cs
When there is a connectivity issue when downloading an S3 object, the whole task is retried.
Add a retry mechanism within the S3 plugin itself to limit the number of task retry consumed in case of connectivity error.
This makes transient network errors transparent. It also reduce the latency of S3 downloading as it avoids a few requests.
=> refactor: Add S3 implicit retry

Adaptors/Memory/src/TaskTable.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Storage/ITaskTable.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/src/Storage/TaskTableExtensions.cs, Common/tests/Helpers/SimpleTaskTable.cs, Common/tests/Pollster/TaskHandlerTest.cs, Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs, Common/tests/TaskLifeCycleHelperTest.cs, Common/tests/TestBase/TaskTableTestBase.cs
If a result is completed during the submission of a dependent task, the task could end-up in a state where all its dependencies are completed, but the task remains pending.
During submission, add a check of the task dependencies after the removal of completed dependencies.
Matrix multiplication with Pymonik was failling frequently before this patch, but always finishes with it.
As dependency resolution incurs a new DB query, it might increase the scheduling overhead and reduce total throughput achievable.
=> fix: Check dependencies at the end of submission

Common/src/HealthCheckRecord.cs, Common/src/Pollster/Pollster.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/HealCheckRecordExt.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Common/tests/Pollster/PollsterTest.cs, Common/tests/Pollster/TaskHandlerTest.cs, Compute/PollingAgent/src/Program.cs
When a cancellation is triggered during a RPC, the RPC throws a `RpcException` instead of an `OperationCanceledException` as expected. Consequently, tasks were retried when the agent was shutting down instead of just being requeued.
The check to know whether we are stopping the agent now also checks `RpcException` when the `InnerException` is an `OperationCanceledException`. It also uses the correct cancellationToken to verify.
This has been tested locally, and a Unit test has been added to ensure both `OperationCanceledException` and `RpcException` are detected.
During scale-down, tasks will now just be requeued without incrementing the retry counter. This will avoid task errors just for being retried too many times while being retried on scaling down pods.
If a task somehow makes the …
=> fix: Properly handle cancellation in worker RPC

Common/src/Pollster/Pollster.cs
During scale down, the Pollster becomes unhealthy because it exists the main loop. If the processing task does not finishes within the grace delay, it will be retried instead of just requeued because of this health check.
Mark the Pollster unhealthy only in the case the loop exits with an exception.
Launch long tasks (through Bench client), and force a scale down using `kubectl scale`. Tasks are requeued properly without being retried, even when the health check happened during the grace period.
=> fix: Avoid unhealthy pollster during downscaling

Common/src/Pollster/Pollster.cs
If too many acquire timeouts happen during the processing of a single task, the currently acquired task will be marked for release, but the release will be effective only once the task handler is disposed, which happens *after* the processing task has finished.
This blocks the task message in the agent for no good reason.
Add task handler dispose before waiting for the next pipeline stage to be ready.
=> fix: Dispose taskHandler on acquire timeout

Common/src/Pollster/TaskHandler.cs, Common/src/Storage/ResultLifeCycleHelper.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/src/gRPC/Services/GrpcTasksService.cs, Common/tests/Submitter/SubmitterTests.cs, Common/tests/TaskLifeCycleHelperTest.cs
While handling a processing task from a crashed pod, if there is no way to complete the task on behalf of the crashed pod, results created by the task were not aborted, and OwnerTaskId of ExpectedOutputKeys were not reset.
Restore the OwnerTaskId and abort all created tasks and results before retrying the task.
The implementation of AbortTasksAndResults has also been refactored to support aborting specific results in addition to tasks.
The reason messages for the abortion have also been adjusted to better reflect the actual reason.
In case of retry after crash, there should be no more cases of pending tasks and results.
Error recovery will be a bit slower because of the additional queries.
=> fix: Abort tasks on retry

Common/src/Pollster/AcquisitionStatus.cs, Common/src/Pollster/TaskHandler.cs, Common/src/Storage/ResultLifeCycleHelper.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/src/Storage/TaskTableExtensions.cs, Common/src/gRPC/Services/Submitter.cs, Common/tests/Pollster/TaskHandlerTest.cs, Common/tests/TaskLifeCycleHelperTest.cs, Common/tests/TestBase/TaskTableTestBase.cs, Common/tests/TestBase/TaskWatcherTestBase.cs
If 2 pods retry the same task, current code makes it that only of them will actually retry the task. In some cases, the pod that should be responsible for the retry crashes, and the retry is never submitted.
Avoid the election of a pod responsible for the retry, and let both of them submit the retry task.
Refactor task ending and retry to mutualize code.
A unit test has been added that start multiple tasks retrying the same task concurrently, for all task status possible, even Retried. The test check that the retried task has successfully been created and submitted to the queue.
This enables error recovery when an agent crashes while creating a retry task.
=> fix: Idem-potent retry

Adaptors/SQS/src/AmazonSQSClient.cs, Adaptors/SQS/src/PullQueueStorage.cs, Adaptors/SQS/src/PushQueueStorage.cs, Adaptors/SQS/src/SQS.cs
SQS supports many options when creating SQS queues that ArmoniK does not expose.
Expose the dictionary config to be passed when creating SQS queues.
Deploying on AWS with attribute to set max message size to 1024 works as expected.
Enable more customization when creating the SQS, be it SQS policy, retention, or KMS configuration.
=> refactor: Expose attributes parameter when creating SQS

terraform/modules/monitoring/seq/main.tf
Added an environment variable to disable Seq’s forced admin authentication on first run.
Allows Seq to start without requiring an admin password, useful for dev/test environments.
=> fix: seq deploiment set correctly

Common/src/DynamicLoading/CollocatedAssemblyResolver.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/DynamicLoading/CollocatedAssemblyResolver.cs.
=> docs: add xml-doc for Common/src/DynamicLoading/CollocatedAssemblyResolver.cs

Common/src/gRPC/Convertors/TaskDataHolderExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/TaskDataHolderExt.cs.
=> docs: add xml-doc for Common/src/gRPC/Convertors/TaskDataHolderExt.cs

Common/src/gRPC/Convertors/SessionStatusExt.cs
Complete code documentation. This PR adds missing xml-doc for the file: Common/src/gRPC/Convertors/SessionStatusExt.cs.
=> docs: add xml-doc for Common/src/gRPC/Convertors/SessionStatusExt.cs

Adaptors/PubSub/src/QueueMessageHandler.cs, Adaptors/SQS/src/QueueMessageHandler.cs
Ensure consistency across queue adapters by standardizing the initial message status.
Sets `Status = QueueMessageStatus.Waiting` as the default for both `SQS` and `PubSub` adapters, aligning them with the behavior of other queues in the system.
Confirmed locally that both adapters produce messages with the correct initial status.
No impact on existing functionality.
* Improves consistency across all queue implementations
* No breaking changes
* Simplifies reasoning and maintenance around message lifecycle
[x] My code adheres to the coding and style guidelines of the project
[x] I have performed a self-review of my code
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have thoroughly tested my modifications and added tests when necessary
[x] Tests pass locally …
=> chore: status is set to default for all queues

Common/src/HealthCheckRecord.cs, Common/src/Pollster/TaskHandler.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs
If pod stopping is requested before the first liveness probe, the report is empty and was considered unhealthy.
HealthCheckRecord is now initialized with an empty *healthy* report.
In case the agent self destroys, the failure status of the exception manager is also checked to consider the agent unhealthy even though the last health check report was healthy.
Unit tests continue to pass.
It should reduce the number of false positive when downscaling too soon.
It is not a fix for the pods staying in the terminating state during the whole duration of the terminationGracePeriod of Kubernetes.
=> fix: Consider application healthy if no health check has ran

.github/workflows/make-release.yml
In some cases, the version computed by codacy does not match what we really want.
Add a possibility to override the release version by specifying a project variable named `OVERRIDE_RELEASE_VERSION` with the expected version.
To be tested for the next release.
The override variable must be emptied after the release.
=> ci: Support for OVERRIDE_RELEASE_VERSION

.github/workflows/make-release.yml
#998 is not implemented correctly, and even though the check pass, the wrong version is used.
Use the tag name instead of the version computed from codacy to publish docker images and nugets.
Will be tested on the next release.
=> ci: Use the tag name instead of the tag computed by codacy

Tests/Stream/Client/TaskSubmissionTests.cs
Improve test reliability. The Stream tests were failing regularly on https://github.com/aneoconsulting/ArmoniK pipelines.
This PRs adds a small delay between the wait for the result completion and the check of the task status as the result change status a little bit before the task change status.
Core pipeline is working fine. We'll see how it goes in the future.
- Less retried tests and less time waiting for failed tests.
=> test: add delay to wait for tasks to have the proper status in Stream tests

.github/workflows/scout-cron.yml
Make sure the pipeline using Docker Scout to check the CVEs of our images is working.
- Matrix provided by another job whould be defined with an `=` not a `:`.
- Use the right field from the matrix to specify the image.
Workflow can also be run manually. Il was tested like so. 
No impact.
=> fix: use valid format to put in github output

.github/workflows/build.yml, Common/src/ArmoniK.Core.Common.csproj
Force documentation writing by failing project build when documentation is missing.
- Enable documentation build in ArmoniK.Core.Common project to check documentation availability
- Add `-warnAsError` flag to convert missing documentation warnings into errors.
Build did not work when documentation was missing. A lot of PRs were added to add missing doc in the meantime.
- Improve projet quality and facilitate proof reading.
=> ci: fail build if xml-doc is not present on public methods

terraform/modules/storage/database/mongo/main.tf, terraform/modules/storage/database/mongo/mongo_init.tpl.js, terraform/modules/storage/database/mongo/outputs.tf
When deploying Core, a MongoDB restart required manually re-inserting the partition data by hand. This process was tedious and error-prone, especially since it was triggered automatically via Terraform. This PR aims to improve deployment resilience and developer experience by automating this step.
This PR integrates the partition insertion logic directly into the MongoDB replica set init script. It includes a loop that waits for the replica set to be ready before proceeding, ensuring a reliable setup even after a database restart.
Tested locally by restarting MongoDB after deployment and verifying that the replica set is correctly initialized and that partition data is inserted automatically without requiring manual intervention.
Improves reliability of deployments involving MongoDB by …
=> chore: embed replica set and partition setup into init script

Adaptors/MongoDB/src/Common/BaseTable.cs, Adaptors/MongoDB/src/PartitionTable.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/SessionTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Storage/IPartitionTable.cs, Common/src/Storage/IResultTable.cs, Common/src/Storage/ISessionTable.cs, Common/src/Storage/ITaskTable.cs, Common/src/gRPC/Services/GrpcApplicationsService.cs, Common/src/gRPC/Services/GrpcEventsService.cs, Common/src/gRPC/Services/GrpcPartitionsService.cs, Common/src/gRPC/Services/GrpcResultsService.cs, Common/src/gRPC/Services/GrpcSessionsService.cs, Common/src/gRPC/Services/GrpcSubmitterService.cs, Common/src/gRPC/Services/GrpcTasksService.cs, Common/tests/Submitter/GrpcSubmitterServiceTests.cs, Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
Monitoring RPCs (like list and count) are heavy on the database, but do not target secondary servers.
This imposes a high load on the primary server, while those RPCs do not require the consistency offered by the primary.
Refactor MongoDB Adapter to mutualize code between tables, and implement read-only optimizations to target read replicas for monitoring services.
Deploy ArmoniK with 3 MongoDB replicas.
Populate the database with many tasks (> 100k), and go to the list of session page on the GUI.
Configure the auto refresh to 0.1s.
With main, only the primary has some loads. with this PR, only secondaries have load.
If there is a single replicas, it still works and the load goes (obviously) to the primary.
Read RPCs are configured to target read replicas. It might be possible to have …
=> refactor: MongoDB BaseTable and read preference

Adaptors/MongoDB/src/Common/SessionProvider.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/SessionTable.cs, Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/PartitionDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/ResultDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/SessionDataModelMapping.cs, Adaptors/MongoDB/src/Table/DataModel/TaskDataModelMapping.cs, Adaptors/MongoDB/src/TaskTable.cs, Adaptors/PubSub/src/QueueBuilder.cs, Adaptors/S3/src/ObjectStorage.cs, Adaptors/SQS/src/QueueBuilder.cs, Compute/PollingAgent/src/Program.cs, Compute/PollingAgent/src/Worker.cs, Control/Metrics/src/ArmoniKMeter.cs, Control/Metrics/src/Program.cs, Control/Submitter/src/Program.cs
We still have warnings about public fields not documented.
Add inheritdoc wherever possible.
Ignore XML doc warnings on Program.
=> docs: Add inherit docs and ignore warning on main

.github/workflows/build.yml
Reduce rate limiting issues during the pull of docker images.
Login to dockerhub to increase the pull limits.
Pipelines do not seem to crash anymore whereas they were crashing once or twice each run.
Improve pipelines reliability and avoid re-running them.
=> chore: login to docker to augment pull rate limits

Common/src/Stream/Worker/WorkerStreamHandler.cs
Improve debuggability
Move channel creation error from Debug to Error logging level.
=> refactor: show logs in error when worker channel failed to create

Dockerfile, Tests/Bench/Client/src/Dockerfile, Tests/Bench/Server/src/Dockerfile, Tests/CrashingWorker/Client/src/Dockerfile, Tests/CrashingWorker/Server/src/Dockerfile, Tests/HtcMock/Client/src/Dockerfile, Tests/HtcMock/Server/src/Dockerfile, Tests/Stream/Client/Dockerfile, Tests/Stream/Server/Dockerfile, justfile, terraform/main.tf, terraform/modules/compute_plane/inputs.tf, terraform/modules/compute_plane/main.tf, terraform/modules/storage/database/mongo/inputs.tf, terraform/modules/storage/database/mongo/main.tf, terraform/variables.tf
Reduce the size of the images and reduce surface of attack.
Use `mcr.microsoft.com/dotnet/aspnet:8.0-azurelinux3.0-distroless` as base image instead of `mcr.microsoft.com/dotnet/aspnet:8.0`. It mainly changes the way the images are constructed:
- Images are minimalist so it is not possible to create new users. We use `$APP_UID` user defined by the image with ID 1654 as of now instead of `armonikuser` with ID 5000.
- The `/cache` folder is not created anymore. Driver options are given to create the volume underneath and make it properly available for the agent and the worker.
The size of the images is reduced by around 100Mo.
- Pipelines in this repo are passing.
- Tests in ArmoniK infrastructure on localhost and in AWS
- Reduced surface of attack and less CVEs
- Smaller images
- For …
=> feat: use dotnet 8 azurelinux3.0 distroless docker images

.github/workflows/build.yml, Adaptors/Nats/src/ArmoniK.Core.Adapters.Nats.csproj, Adaptors/Nats/src/Heart.cs, Adaptors/Nats/src/Nats.cs, Adaptors/Nats/src/PullQueueStorage.cs, Adaptors/Nats/src/PushQueueStorage.cs, Adaptors/Nats/src/QueueBuilder.cs, Adaptors/Nats/src/QueueMessageHandler.cs, ArmoniK.Core.sln, Base/tests/Queue/QueueStorageTests.cs, Dockerfile, justfile, terraform/locals.tf, terraform/main.tf, terraform/modules/storage/queue/nats/inputs.tf, terraform/modules/storage/queue/nats/main.tf, terraform/modules/storage/queue/nats/outputs.tf, terraform/modules/storage/queue/nats/versions.tf, terraform/variables.tf
**Motivation**
Add NATS as a supported queue system in ArmoniK to leverage JetStream for in-flight message handling. This enables high-throughput, durable message processing while maintaining the same pull/push and queue handler patterns used by other queue systems.
**Description**
* Implemented a NATS adapter with both `PushMessagesAsync` and `PullMessagesAsync` methods.
* Introduced a `QueueMessageHandler` for NATS messages to handle acknowledgement and auto-extend deadlines.
* Added a `Heart` mechanism for monitoring message processing.
* Exposed configuration options: `AckWait` and `AckExtendDeadlineStep` to control ack timing, `DegreeOfParallelism` to limit parrallelism in operation.
* Integrated NATS into the list of available queues in ArmoniK.
**Testing**
* Verified push and pull …
=> feat: Add NATS adapter with JetStream support to ArmoniK queues

.github/workflows/build.yml, justfile, terraform/main.tf, terraform/modules/storage/queue/nats/inputs.tf, terraform/modules/storage/queue/nats/main.tf
L’image Windows utilisée pour RabbitMQ n’était pas officielle et pouvait poser des problèmes de maintenance et de sécurité. À l’inverse, NATS dispose d’une image officielle Windows, ce qui justifie son ajout.
* Suppression de l’image Windows non officielle pour RabbitMQ.
* Ajout de l’image Windows officielle pour NATS.
Ces changements visent à standardiser l’utilisation d’images officielles et maintenues.
* Vérification du bon démarrage des conteneurs avec la nouvelle configuration.
* Tests de connectivité et de fonctionnement des files de messages sous Linux et Windows.
*Rabbitmq ne supporte plus windows.
*Nats supporte windows.
* Pas d’impact attendu sur la configuration ou les performances globales d’ArmoniK.
Le changement de queue va modifier les performances lier sur Windows.
=> chore: change rabbitmq for windows to nats for windows

.docs/content/1.concepts/4.adaptors.md, Adaptors/README.md, README.md
ArmoniK recently introduced support for NATS as a messaging backend, but the documentation did not reflect this addition. Furthermore, information about the missing queue handling mechanism was incomplete. Clear and updated documentation is essential for both contributors and users to understand available backends and queue options.
* Adding NATS as a supported queue backend in the official docs.
* Completing the missing documentation for the queue configuration and behavior, including how missing queues are managed.
* Ensuring consistency across documentation sections where supported queues are listed or explained.
* **Documentation:** Improves user understanding by covering missing queue cases explicitly.
=> docs: Add Nats to doc and upgrade queue documentation

README.md
The previous documentation link was outdated and still pointed to the GitHub Pages site, whereas we have migrated to ReadTheDocs.
Updated the documentation link to point to the new ReadTheDocs URL.
Verified that the new link is working correctly.
The documentation link now correctly directs users to the latest ReadTheDocs version.
=> docs: wrong link in README.md

Adaptors/Memory/src/ResultTable.cs, Adaptors/Memory/src/TaskTable.cs, Adaptors/MongoDB/src/ResultTable.cs, Adaptors/MongoDB/src/TaskTable.cs, Common/src/Storage/IResultTable.cs, Common/src/Storage/ITaskTable.cs, Common/src/Storage/TaskLifeCycleHelper.cs, Common/src/gRPC/Services/GrpcResultsService.cs, Common/src/gRPC/Services/GrpcSubmitterService.cs, Common/src/gRPC/Services/GrpcTasksService.cs, Common/tests/GrpcResultsServiceTests.cs, Common/tests/GrpcTasksServiceTests.cs, Common/tests/Helpers/SimpleResultTable.cs, Common/tests/Helpers/SimpleTaskTable.cs, Common/tests/Pollster/DataPrefetcherTest.cs, Common/tests/Pollster/TaskHandlerTest.cs, Common/tests/Submitter/GrpcSubmitterServiceTests.cs, Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs, Common/tests/TaskLifeCycleHelperTest.cs
We observed cases of tasks that were not properly submitted due to interruptions or errors during submission. This PR aims to make submission related RPCs atomic so that, when there is an issue, no tasks or results are left in an inconsistent state.
A try/catch block was added around critical parts of the code where the tasks/resutls are deleted from the database/object storage upon exception.
Unit tests were implemented to check that tasks and results are properly deleted.
- Tasks that are in Pending state due to errors during submission should be deleted and not appear in monitoring anymore.
- Issues during result creation should not leave partial results created
- Rollback after task submission by another task is not properly implemented because owner id in the result is changed …
=> fix: tasks and results creation should be atomic

Adaptors/S3/src/ObjectStorage.cs
Actually retry when there is a connection issue during object download in S3 adapter.
Retry where implemented on AmazonS3Exception which is not thrown in every case. HttpResquestException are also emitted. This PR also enable retries when this exception occurs.
- No particular test were added because we see this exception appear in logs on production.
- Make ArmoniK more resilient.
=> fix: retry on the proper exception in S3 adapter

Adaptors/SQS/src/PullQueueStorage.cs, Adaptors/SQS/src/QueueMessageHandler.cs, Adaptors/SQS/src/SQS.cs
Improve the likelihood to extend on flight message deadline when there is an issue. This reduce the probability of a message representing a task in Processing being redistributed while still being processed elsewhere by an agent that was not able to extend the deadline for some reason.
Add a loop to retry message deadline extension.
- Pipelines are passing.
- More extensive testing will be made later on where a few more fixes will be implemented.
- Improve ArmoniK stability during connection issues with SQS. For instance, DNS issues that impede acces to AWS services.
=> fix: retry message deadline extension in SQS adapter

Common/src/Injection/ServiceCollectionExt.cs, Common/src/Pollster/Pollster.cs, Common/src/Pollster/PostProcessor.cs, Common/src/Pollster/RunningTaskProcessor.cs, Common/src/Utils/ExceptionManager.cs, Common/tests/ExceptionManagerTests.cs, Common/tests/Helpers/TestPollsterProvider.cs, Common/tests/Helpers/TestTaskHandlerProvider.cs, Compute/PollingAgent/src/Program.cs, Control/Submitter/src/Program.cs
During agent shut down, a SIGTERM is sent to it, triggering graceful shutdown. At this point, kestrel server is disabled and do not respond to `/taskprocessing`, `/cancelled`, `/liveness` etc endpoints. This is an issue because `/taskprocessing` is used in message deduplication.
When the SIGTERM occurs, the agent still processes a task until the GraceDelay. During this time, the message representing the task can be redistributed and the other agent will try to check if the task is still being processed by the former agent by calling its `/taskprocessing`. The former agent will not respond while still processing the task. This can cause tasks being executed twice.
The ExceptionManager was made to implement `IHostLifetime` and `IApplicationLifetime` to properly delay actual shut down of the …
=> fix: keep server kestrel on after SIGTERM until Pollster grace delay
